main: com.cavetale.core.CorePlugin

name: Core
version: 0.1
description: Cavetale Core Plugin. Libraries and runtime components.
api-version: 1.17

author: StarTux
website: https://github.com/StarTux/Core

depend: []
softdepend: []
