main: com.cavetale.core.CorePlugin

name: Core
version: 0.1
description: Cavetale Core Plugin. Libraries and runtime components.
api-version: '1.21.8'

author: StarTux
website: https://github.com/StarTux/Core

depend: []
softdepend: []

commands:

  core:
    description: Core command
    permission: core.admin
    usage: /core

permissions:

  core.admin:
    description: Use /core
    default: op