package com.cavetale.core.font;

import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import lombok.Getter;
import net.kyori.adventure.key.Key;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.Style;
import net.kyori.adventure.text.format.TextColor;
import org.bukkit.Material;

/**
 * This is a list generated by CavetaleResourcePack. It will be added
 * to cavetale:default font.
 * Unicode character codes start at 0xE400.
 */
@Getter
public enum VanillaItems implements Font {
    ACACIA_BOAT(Material.ACACIA_BOAT, "minecraft:item/acacia_boat", 8, 8, 1, '\uE400'),
    ACACIA_DOOR(Material.ACACIA_DOOR, "minecraft:item/acacia_door", 8, 8, 1, '\uE401'),
    ACACIA_LEAVES(Material.ACACIA_LEAVES, "minecraft:block/acacia_leaves", 8, 8, 1, '\uE402'),
    ACACIA_LOG(Material.ACACIA_LOG, "minecraft:block/acacia_log", 8, 8, 1, '\uE403'),
    ACACIA_PLANKS(Material.ACACIA_PLANKS, "minecraft:block/acacia_planks", 8, 8, 1, '\uE404'),
    ACACIA_SAPLING(Material.ACACIA_SAPLING, "minecraft:block/acacia_sapling", 8, 8, 1, '\uE405'),
    ACACIA_SIGN(Material.ACACIA_SIGN, "minecraft:item/acacia_sign", 8, 8, 1, '\uE406'),
    ACACIA_TRAPDOOR(Material.ACACIA_TRAPDOOR, "minecraft:block/acacia_trapdoor", 8, 8, 1, '\uE407'),
    ACTIVATOR_RAIL(Material.ACTIVATOR_RAIL, "minecraft:block/activator_rail", 8, 8, 1, '\uE408'),
    ALLIUM(Material.ALLIUM, "minecraft:block/allium", 8, 8, 1, '\uE409'),
    AMETHYST_BLOCK(Material.AMETHYST_BLOCK, "minecraft:block/amethyst_block", 8, 8, 1, '\uE691'),
    AMETHYST_CLUSTER(Material.AMETHYST_CLUSTER, "minecraft:block/amethyst_cluster", 8, 8, 1, '\uE692'),
    AMETHYST_SHARD(Material.AMETHYST_SHARD, "minecraft:item/amethyst_shard", 8, 8, 1, '\uE693'),
    ANCIENT_DEBRIS(Material.ANCIENT_DEBRIS, "minecraft:block/ancient_debris_side", 8, 8, 1, '\uE40A'),
    ANDESITE(Material.ANDESITE, "minecraft:block/andesite", 8, 8, 1, '\uE40B'),
    ANVIL(Material.ANVIL, "minecraft:block/anvil", 8, 8, 1, '\uE40C'),
    APPLE(Material.APPLE, "minecraft:item/apple", 8, 8, 1, '\uE40D'),
    ARMOR_STAND(Material.ARMOR_STAND, "minecraft:item/armor_stand", 8, 8, 1, '\uE40E'),
    ARROW(Material.ARROW, "minecraft:item/arrow", 8, 8, 1, '\uE40F'),
    ATTACHED_MELON_STEM(Material.ATTACHED_MELON_STEM, "minecraft:block/attached_melon_stem", 8, 8, 1, '\uE410'),
    ATTACHED_PUMPKIN_STEM(Material.ATTACHED_PUMPKIN_STEM, "minecraft:block/attached_pumpkin_stem", 8, 8, 1, '\uE411'),
    AXOLOTL_BUCKET(Material.AXOLOTL_BUCKET, "minecraft:item/axolotl_bucket", 8, 8, 1, '\uE694'),
    AZALEA(Material.AZALEA, "minecraft:block/azalea_side", 8, 8, 1, '\uE695'),
    AZALEA_LEAVES(Material.AZALEA_LEAVES, "minecraft:block/azalea_leaves", 8, 8, 1, '\uE696'),
    AZURE_BLUET(Material.AZURE_BLUET, "minecraft:block/azure_bluet", 8, 8, 1, '\uE412'),
    BAKED_POTATO(Material.BAKED_POTATO, "minecraft:item/baked_potato", 8, 8, 1, '\uE413'),
    BAMBOO(Material.BAMBOO, "minecraft:item/bamboo", 8, 8, 1, '\uE414'),
    BARREL(Material.BARREL, "minecraft:block/barrel_side", 8, 8, 1, '\uE415'),
    BARRIER(Material.BARRIER, "minecraft:item/barrier", 8, 8, 1, '\uE416'),
    BASALT(Material.BASALT, "minecraft:block/basalt_side", 8, 8, 1, '\uE417'),
    BEACON(Material.BEACON, "minecraft:block/beacon", 8, 8, 1, '\uE418'),
    BEDROCK(Material.BEDROCK, "minecraft:block/bedrock", 8, 8, 1, '\uE419'),
    BEEF(Material.BEEF, "minecraft:item/beef", 8, 8, 1, '\uE41A'),
    BEEHIVE(Material.BEEHIVE, "minecraft:block/beehive_front", 8, 8, 1, '\uE41B'),
    BEETROOT(Material.BEETROOT, "minecraft:item/beetroot", 8, 8, 1, '\uE41C'),
    BEETROOT_SEEDS(Material.BEETROOT_SEEDS, "minecraft:item/beetroot_seeds", 8, 8, 1, '\uE41D'),
    BEETROOT_SOUP(Material.BEETROOT_SOUP, "minecraft:item/beetroot_soup", 8, 8, 1, '\uE41E'),
    BEE_NEST(Material.BEE_NEST, "minecraft:block/bee_nest_front", 8, 8, 1, '\uE41F'),
    BELL(Material.BELL, "minecraft:item/bell", 8, 8, 1, '\uE420'),
    BIG_DRIPLEAF(Material.BIG_DRIPLEAF, "minecraft:block/big_dripleaf_top", 8, 8, 1, '\uE697'),
    BIG_DRIPLEAF_STEM(Material.BIG_DRIPLEAF_STEM, "minecraft:block/big_dripleaf_stem", 8, 8, 1, '\uE698'),
    BIRCH_BOAT(Material.BIRCH_BOAT, "minecraft:item/birch_boat", 8, 8, 1, '\uE421'),
    BIRCH_DOOR(Material.BIRCH_DOOR, "minecraft:item/birch_door", 8, 8, 1, '\uE422'),
    BIRCH_LEAVES(Material.BIRCH_LEAVES, "minecraft:block/birch_leaves", 8, 8, 1, '\uE423'),
    BIRCH_LOG(Material.BIRCH_LOG, "minecraft:block/birch_log", 8, 8, 1, '\uE424'),
    BIRCH_PLANKS(Material.BIRCH_PLANKS, "minecraft:block/birch_planks", 8, 8, 1, '\uE425'),
    BIRCH_SAPLING(Material.BIRCH_SAPLING, "minecraft:block/birch_sapling", 8, 8, 1, '\uE426'),
    BIRCH_SIGN(Material.BIRCH_SIGN, "minecraft:item/birch_sign", 8, 8, 1, '\uE427'),
    BIRCH_TRAPDOOR(Material.BIRCH_TRAPDOOR, "minecraft:block/birch_trapdoor", 8, 8, 1, '\uE428'),
    BLACKSTONE(Material.BLACKSTONE, "minecraft:block/blackstone", 8, 8, 1, '\uE429'),
    BLACK_CANDLE(Material.BLACK_CANDLE, "minecraft:item/black_candle", 8, 8, 1, '\uE699'),
    BLACK_CONCRETE(Material.BLACK_CONCRETE, "minecraft:block/black_concrete", 8, 8, 1, '\uE42A'),
    BLACK_CONCRETE_POWDER(Material.BLACK_CONCRETE_POWDER, "minecraft:block/black_concrete_powder", 8, 8, 1, '\uE42B'),
    BLACK_DYE(Material.BLACK_DYE, "minecraft:item/black_dye", 8, 8, 1, '\uE42C'),
    BLACK_GLAZED_TERRACOTTA(Material.BLACK_GLAZED_TERRACOTTA, "minecraft:block/black_glazed_terracotta", 8, 8, 1, '\uE42D'),
    BLACK_SHULKER_BOX(Material.BLACK_SHULKER_BOX, "minecraft:block/black_shulker_box", 8, 8, 1, '\uE42E'),
    BLACK_STAINED_GLASS(Material.BLACK_STAINED_GLASS, "minecraft:block/black_stained_glass", 8, 8, 1, '\uE42F'),
    BLACK_STAINED_GLASS_PANE(Material.BLACK_STAINED_GLASS_PANE, "minecraft:block/black_stained_glass_pane_top", 8, 8, 1, '\uE6FA'),
    BLACK_TERRACOTTA(Material.BLACK_TERRACOTTA, "minecraft:block/black_terracotta", 8, 8, 1, '\uE430'),
    BLACK_WOOL(Material.BLACK_WOOL, "minecraft:block/black_wool", 8, 8, 1, '\uE431'),
    BLAST_FURNACE(Material.BLAST_FURNACE, "minecraft:block/blast_furnace_front", 8, 8, 1, '\uE432'),
    BLAZE_POWDER(Material.BLAZE_POWDER, "minecraft:item/blaze_powder", 8, 8, 1, '\uE433'),
    BLAZE_ROD(Material.BLAZE_ROD, "minecraft:item/blaze_rod", 8, 8, 1, '\uE434'),
    BLUE_CANDLE(Material.BLUE_CANDLE, "minecraft:item/blue_candle", 8, 8, 1, '\uE69A'),
    BLUE_CONCRETE(Material.BLUE_CONCRETE, "minecraft:block/blue_concrete", 8, 8, 1, '\uE435'),
    BLUE_CONCRETE_POWDER(Material.BLUE_CONCRETE_POWDER, "minecraft:block/blue_concrete_powder", 8, 8, 1, '\uE436'),
    BLUE_DYE(Material.BLUE_DYE, "minecraft:item/blue_dye", 8, 8, 1, '\uE437'),
    BLUE_GLAZED_TERRACOTTA(Material.BLUE_GLAZED_TERRACOTTA, "minecraft:block/blue_glazed_terracotta", 8, 8, 1, '\uE438'),
    BLUE_ICE(Material.BLUE_ICE, "minecraft:block/blue_ice", 8, 8, 1, '\uE439'),
    BLUE_ORCHID(Material.BLUE_ORCHID, "minecraft:block/blue_orchid", 8, 8, 1, '\uE43A'),
    BLUE_SHULKER_BOX(Material.BLUE_SHULKER_BOX, "minecraft:block/blue_shulker_box", 8, 8, 1, '\uE43B'),
    BLUE_STAINED_GLASS(Material.BLUE_STAINED_GLASS, "minecraft:block/blue_stained_glass", 8, 8, 1, '\uE43C'),
    BLUE_STAINED_GLASS_PANE(Material.BLUE_STAINED_GLASS_PANE, "minecraft:block/blue_stained_glass_pane_top", 8, 8, 1, '\uE6FB'),
    BLUE_TERRACOTTA(Material.BLUE_TERRACOTTA, "minecraft:block/blue_terracotta", 8, 8, 1, '\uE43D'),
    BLUE_WOOL(Material.BLUE_WOOL, "minecraft:block/blue_wool", 8, 8, 1, '\uE43E'),
    BONE(Material.BONE, "minecraft:item/bone", 8, 8, 1, '\uE43F'),
    BONE_BLOCK(Material.BONE_BLOCK, "minecraft:block/bone_block_side", 8, 8, 1, '\uE440'),
    BONE_MEAL(Material.BONE_MEAL, "minecraft:item/bone_meal", 8, 8, 1, '\uE441'),
    BOOK(Material.BOOK, "minecraft:item/book", 8, 8, 1, '\uE442'),
    BOOKSHELF(Material.BOOKSHELF, "minecraft:block/bookshelf", 8, 8, 1, '\uE443'),
    BOW(Material.BOW, "minecraft:item/bow", 8, 8, 1, '\uE444'),
    BOWL(Material.BOWL, "minecraft:item/bowl", 8, 8, 1, '\uE445'),
    BRAIN_CORAL(Material.BRAIN_CORAL, "minecraft:block/brain_coral", 8, 8, 1, '\uE446'),
    BRAIN_CORAL_BLOCK(Material.BRAIN_CORAL_BLOCK, "minecraft:block/brain_coral_block", 8, 8, 1, '\uE447'),
    BRAIN_CORAL_FAN(Material.BRAIN_CORAL_FAN, "minecraft:block/brain_coral_fan", 8, 8, 1, '\uE448'),
    BREAD(Material.BREAD, "minecraft:item/bread", 8, 8, 1, '\uE449'),
    BREWING_STAND(Material.BREWING_STAND, "minecraft:item/brewing_stand", 8, 8, 1, '\uE44A'),
    BRICK(Material.BRICK, "minecraft:item/brick", 8, 8, 1, '\uE44B'),
    BRICKS(Material.BRICKS, "minecraft:block/bricks", 8, 8, 1, '\uE44C'),
    BROWN_CANDLE(Material.BROWN_CANDLE, "minecraft:item/brown_candle", 8, 8, 1, '\uE69B'),
    BROWN_CONCRETE(Material.BROWN_CONCRETE, "minecraft:block/brown_concrete", 8, 8, 1, '\uE44D'),
    BROWN_CONCRETE_POWDER(Material.BROWN_CONCRETE_POWDER, "minecraft:block/brown_concrete_powder", 8, 8, 1, '\uE44E'),
    BROWN_DYE(Material.BROWN_DYE, "minecraft:item/brown_dye", 8, 8, 1, '\uE44F'),
    BROWN_GLAZED_TERRACOTTA(Material.BROWN_GLAZED_TERRACOTTA, "minecraft:block/brown_glazed_terracotta", 8, 8, 1, '\uE450'),
    BROWN_MUSHROOM(Material.BROWN_MUSHROOM, "minecraft:block/brown_mushroom", 8, 8, 1, '\uE451'),
    BROWN_MUSHROOM_BLOCK(Material.BROWN_MUSHROOM_BLOCK, "minecraft:block/brown_mushroom_block", 8, 8, 1, '\uE452'),
    BROWN_SHULKER_BOX(Material.BROWN_SHULKER_BOX, "minecraft:block/brown_shulker_box", 8, 8, 1, '\uE453'),
    BROWN_STAINED_GLASS(Material.BROWN_STAINED_GLASS, "minecraft:block/brown_stained_glass", 8, 8, 1, '\uE454'),
    BROWN_STAINED_GLASS_PANE(Material.BROWN_STAINED_GLASS_PANE, "minecraft:block/brown_stained_glass_pane_top", 8, 8, 1, '\uE6FC'),
    BROWN_TERRACOTTA(Material.BROWN_TERRACOTTA, "minecraft:block/brown_terracotta", 8, 8, 1, '\uE455'),
    BROWN_WOOL(Material.BROWN_WOOL, "minecraft:block/brown_wool", 8, 8, 1, '\uE456'),
    BUBBLE_CORAL(Material.BUBBLE_CORAL, "minecraft:block/bubble_coral", 8, 8, 1, '\uE457'),
    BUBBLE_CORAL_BLOCK(Material.BUBBLE_CORAL_BLOCK, "minecraft:block/bubble_coral_block", 8, 8, 1, '\uE458'),
    BUBBLE_CORAL_FAN(Material.BUBBLE_CORAL_FAN, "minecraft:block/bubble_coral_fan", 8, 8, 1, '\uE459'),
    BUCKET(Material.BUCKET, "minecraft:item/bucket", 8, 8, 1, '\uE45A'),
    BUDDING_AMETHYST(Material.BUDDING_AMETHYST, "minecraft:block/budding_amethyst", 8, 8, 1, '\uE69C'),
    BUNDLE(Material.BUNDLE, "minecraft:item/bundle", 8, 8, 1, '\uE69D'),
    CACTUS(Material.CACTUS, "minecraft:block/cactus_side", 8, 8, 1, '\uE45B'),
    CAKE(Material.CAKE, "minecraft:item/cake", 8, 8, 1, '\uE45C'),
    CALCITE(Material.CALCITE, "minecraft:block/calcite", 8, 8, 1, '\uE69E'),
    CAMPFIRE(Material.CAMPFIRE, "minecraft:item/campfire", 8, 8, 1, '\uE45D'),
    CANDLE(Material.CANDLE, "minecraft:item/candle", 8, 8, 1, '\uE69F'),
    CARROT(Material.CARROT, "minecraft:item/carrot", 8, 8, 1, '\uE45E'),
    CARROT_ON_A_STICK(Material.CARROT_ON_A_STICK, "minecraft:item/carrot_on_a_stick", 8, 8, 1, '\uE45F'),
    CARTOGRAPHY_TABLE(Material.CARTOGRAPHY_TABLE, "minecraft:block/cartography_table_side1", 8, 8, 1, '\uE6F5'),
    CARVED_PUMPKIN(Material.CARVED_PUMPKIN, "minecraft:block/carved_pumpkin", 8, 8, 1, '\uE460'),
    CAULDRON(Material.CAULDRON, "minecraft:item/cauldron", 8, 8, 1, '\uE461'),
    CAVE_VINES(Material.CAVE_VINES, "minecraft:block/cave_vines", 8, 8, 1, '\uE6A0'),
    CAVE_VINES_PLANT(Material.CAVE_VINES_PLANT, "minecraft:block/cave_vines_plant", 8, 8, 1, '\uE6A1'),
    CHAIN(Material.CHAIN, "minecraft:item/chain", 8, 8, 1, '\uE462'),
    CHAINMAIL_BOOTS(Material.CHAINMAIL_BOOTS, "minecraft:item/chainmail_boots", 8, 8, 1, '\uE463'),
    CHAINMAIL_CHESTPLATE(Material.CHAINMAIL_CHESTPLATE, "minecraft:item/chainmail_chestplate", 8, 8, 1, '\uE464'),
    CHAINMAIL_HELMET(Material.CHAINMAIL_HELMET, "minecraft:item/chainmail_helmet", 8, 8, 1, '\uE465'),
    CHAINMAIL_LEGGINGS(Material.CHAINMAIL_LEGGINGS, "minecraft:item/chainmail_leggings", 8, 8, 1, '\uE466'),
    CHAIN_COMMAND_BLOCK(Material.CHAIN_COMMAND_BLOCK, "minecraft:block/chain_command_block_front", 8, 8, 4, '\uE6ED'),
    CHARCOAL(Material.CHARCOAL, "minecraft:item/charcoal", 8, 8, 1, '\uE467'),
    CHEST_MINECART(Material.CHEST_MINECART, "minecraft:item/chest_minecart", 8, 8, 1, '\uE468'),
    CHICKEN(Material.CHICKEN, "minecraft:item/chicken", 8, 8, 1, '\uE469'),
    CHIPPED_ANVIL(Material.CHIPPED_ANVIL, "minecraft:block/chipped_anvil_top", 8, 8, 1, '\uE6FD'),
    CHISELED_DEEPSLATE(Material.CHISELED_DEEPSLATE, "minecraft:block/chiseled_deepslate", 8, 8, 1, '\uE6A2'),
    CHISELED_NETHER_BRICKS(Material.CHISELED_NETHER_BRICKS, "minecraft:block/chiseled_nether_bricks", 8, 8, 1, '\uE46A'),
    CHISELED_POLISHED_BLACKSTONE(Material.CHISELED_POLISHED_BLACKSTONE, "minecraft:block/chiseled_polished_blackstone", 8, 8, 1, '\uE46B'),
    CHISELED_QUARTZ_BLOCK(Material.CHISELED_QUARTZ_BLOCK, "minecraft:block/chiseled_quartz_block", 8, 8, 1, '\uE46C'),
    CHISELED_RED_SANDSTONE(Material.CHISELED_RED_SANDSTONE, "minecraft:block/chiseled_red_sandstone", 8, 8, 1, '\uE46D'),
    CHISELED_SANDSTONE(Material.CHISELED_SANDSTONE, "minecraft:block/chiseled_sandstone", 8, 8, 1, '\uE46E'),
    CHISELED_STONE_BRICKS(Material.CHISELED_STONE_BRICKS, "minecraft:block/chiseled_stone_bricks", 8, 8, 1, '\uE46F'),
    CHORUS_FLOWER(Material.CHORUS_FLOWER, "minecraft:block/chorus_flower", 8, 8, 1, '\uE470'),
    CHORUS_FRUIT(Material.CHORUS_FRUIT, "minecraft:item/chorus_fruit", 8, 8, 1, '\uE471'),
    CHORUS_PLANT(Material.CHORUS_PLANT, "minecraft:block/chorus_plant", 8, 8, 1, '\uE472'),
    CLAY(Material.CLAY, "minecraft:block/clay", 8, 8, 1, '\uE473'),
    CLAY_BALL(Material.CLAY_BALL, "minecraft:item/clay_ball", 8, 8, 1, '\uE474'),
    CLOCK(Material.CLOCK, "minecraft:item/clock_00", 8, 8, 1, '\uE6EA'),
    COAL(Material.COAL, "minecraft:item/coal", 8, 8, 1, '\uE475'),
    COAL_BLOCK(Material.COAL_BLOCK, "minecraft:block/coal_block", 8, 8, 1, '\uE476'),
    COAL_ORE(Material.COAL_ORE, "minecraft:block/coal_ore", 8, 8, 1, '\uE477'),
    COARSE_DIRT(Material.COARSE_DIRT, "minecraft:block/coarse_dirt", 8, 8, 1, '\uE478'),
    COBBLED_DEEPSLATE(Material.COBBLED_DEEPSLATE, "minecraft:block/cobbled_deepslate", 8, 8, 1, '\uE6A3'),
    COBBLESTONE(Material.COBBLESTONE, "minecraft:block/cobblestone", 8, 8, 1, '\uE479'),
    COBWEB(Material.COBWEB, "minecraft:block/cobweb", 8, 8, 1, '\uE47A'),
    COCOA_BEANS(Material.COCOA_BEANS, "minecraft:item/cocoa_beans", 8, 8, 1, '\uE47B'),
    COD(Material.COD, "minecraft:item/cod", 8, 8, 1, '\uE47C'),
    COD_BUCKET(Material.COD_BUCKET, "minecraft:item/cod_bucket", 8, 8, 1, '\uE47D'),
    COMMAND_BLOCK(Material.COMMAND_BLOCK, "minecraft:block/command_block_front", 8, 8, 4, '\uE6EE'),
    COMMAND_BLOCK_MINECART(Material.COMMAND_BLOCK_MINECART, "minecraft:item/command_block_minecart", 8, 8, 1, '\uE47E'),
    COMPARATOR(Material.COMPARATOR, "minecraft:item/comparator", 8, 8, 1, '\uE47F'),
    COMPASS(Material.COMPASS, "minecraft:item/compass_16", 8, 8, 1, '\uE6EB'),
    COMPOSTER(Material.COMPOSTER, "minecraft:block/composter_side", 8, 8, 1, '\uE480'),
    CONDUIT(Material.CONDUIT, "minecraft:block/conduit", 8, 8, 1, '\uE481'),
    COOKED_BEEF(Material.COOKED_BEEF, "minecraft:item/cooked_beef", 8, 8, 1, '\uE482'),
    COOKED_CHICKEN(Material.COOKED_CHICKEN, "minecraft:item/cooked_chicken", 8, 8, 1, '\uE483'),
    COOKED_COD(Material.COOKED_COD, "minecraft:item/cooked_cod", 8, 8, 1, '\uE484'),
    COOKED_MUTTON(Material.COOKED_MUTTON, "minecraft:item/cooked_mutton", 8, 8, 1, '\uE485'),
    COOKED_PORKCHOP(Material.COOKED_PORKCHOP, "minecraft:item/cooked_porkchop", 8, 8, 1, '\uE486'),
    COOKED_RABBIT(Material.COOKED_RABBIT, "minecraft:item/cooked_rabbit", 8, 8, 1, '\uE487'),
    COOKED_SALMON(Material.COOKED_SALMON, "minecraft:item/cooked_salmon", 8, 8, 1, '\uE488'),
    COOKIE(Material.COOKIE, "minecraft:item/cookie", 8, 8, 1, '\uE489'),
    COPPER_BLOCK(Material.COPPER_BLOCK, "minecraft:block/copper_block", 8, 8, 1, '\uE6A4'),
    COPPER_INGOT(Material.COPPER_INGOT, "minecraft:item/copper_ingot", 8, 8, 1, '\uE6A5'),
    COPPER_ORE(Material.COPPER_ORE, "minecraft:block/copper_ore", 8, 8, 1, '\uE6A6'),
    CORNFLOWER(Material.CORNFLOWER, "minecraft:block/cornflower", 8, 8, 1, '\uE48A'),
    CRACKED_DEEPSLATE_BRICKS(Material.CRACKED_DEEPSLATE_BRICKS, "minecraft:block/cracked_deepslate_bricks", 8, 8, 1, '\uE6A7'),
    CRACKED_DEEPSLATE_TILES(Material.CRACKED_DEEPSLATE_TILES, "minecraft:block/cracked_deepslate_tiles", 8, 8, 1, '\uE6A8'),
    CRACKED_NETHER_BRICKS(Material.CRACKED_NETHER_BRICKS, "minecraft:block/cracked_nether_bricks", 8, 8, 1, '\uE48B'),
    CRACKED_POLISHED_BLACKSTONE_BRICKS(Material.CRACKED_POLISHED_BLACKSTONE_BRICKS, "minecraft:block/cracked_polished_blackstone_bricks", 8, 8, 1, '\uE48C'),
    CRACKED_STONE_BRICKS(Material.CRACKED_STONE_BRICKS, "minecraft:block/cracked_stone_bricks", 8, 8, 1, '\uE48D'),
    CRAFTING_TABLE(Material.CRAFTING_TABLE, "minecraft:block/crafting_table_front", 8, 8, 1, '\uE48E'),
    CREEPER_BANNER_PATTERN(Material.CREEPER_BANNER_PATTERN, "minecraft:item/creeper_banner_pattern", 8, 8, 1, '\uE48F'),
    CRIMSON_DOOR(Material.CRIMSON_DOOR, "minecraft:item/crimson_door", 8, 8, 1, '\uE490'),
    CRIMSON_FUNGUS(Material.CRIMSON_FUNGUS, "minecraft:block/crimson_fungus", 8, 8, 1, '\uE491'),
    CRIMSON_NYLIUM(Material.CRIMSON_NYLIUM, "minecraft:block/crimson_nylium", 8, 8, 1, '\uE492'),
    CRIMSON_PLANKS(Material.CRIMSON_PLANKS, "minecraft:block/crimson_planks", 8, 8, 1, '\uE493'),
    CRIMSON_ROOTS(Material.CRIMSON_ROOTS, "minecraft:block/crimson_roots", 8, 8, 1, '\uE494'),
    CRIMSON_SIGN(Material.CRIMSON_SIGN, "minecraft:item/crimson_sign", 8, 8, 1, '\uE495'),
    CRIMSON_STEM(Material.CRIMSON_STEM, "minecraft:block/crimson_stem", 8, 8, 5, '\uE6EF'),
    CRIMSON_TRAPDOOR(Material.CRIMSON_TRAPDOOR, "minecraft:block/crimson_trapdoor", 8, 8, 1, '\uE496'),
    CROSSBOW(Material.CROSSBOW, "minecraft:item/crossbow_standby", 8, 8, 1, '\uE6EC'),
    CRYING_OBSIDIAN(Material.CRYING_OBSIDIAN, "minecraft:block/crying_obsidian", 8, 8, 1, '\uE497'),
    CUT_COPPER(Material.CUT_COPPER, "minecraft:block/cut_copper", 8, 8, 1, '\uE6A9'),
    CUT_RED_SANDSTONE(Material.CUT_RED_SANDSTONE, "minecraft:block/cut_red_sandstone", 8, 8, 1, '\uE498'),
    CUT_SANDSTONE(Material.CUT_SANDSTONE, "minecraft:block/cut_sandstone", 8, 8, 1, '\uE499'),
    CYAN_CANDLE(Material.CYAN_CANDLE, "minecraft:item/cyan_candle", 8, 8, 1, '\uE6AA'),
    CYAN_CONCRETE(Material.CYAN_CONCRETE, "minecraft:block/cyan_concrete", 8, 8, 1, '\uE49A'),
    CYAN_CONCRETE_POWDER(Material.CYAN_CONCRETE_POWDER, "minecraft:block/cyan_concrete_powder", 8, 8, 1, '\uE49B'),
    CYAN_DYE(Material.CYAN_DYE, "minecraft:item/cyan_dye", 8, 8, 1, '\uE49C'),
    CYAN_GLAZED_TERRACOTTA(Material.CYAN_GLAZED_TERRACOTTA, "minecraft:block/cyan_glazed_terracotta", 8, 8, 1, '\uE49D'),
    CYAN_SHULKER_BOX(Material.CYAN_SHULKER_BOX, "minecraft:block/cyan_shulker_box", 8, 8, 1, '\uE49E'),
    CYAN_STAINED_GLASS(Material.CYAN_STAINED_GLASS, "minecraft:block/cyan_stained_glass", 8, 8, 1, '\uE49F'),
    CYAN_STAINED_GLASS_PANE(Material.CYAN_STAINED_GLASS_PANE, "minecraft:block/cyan_stained_glass_pane_top", 8, 8, 1, '\uE6FE'),
    CYAN_TERRACOTTA(Material.CYAN_TERRACOTTA, "minecraft:block/cyan_terracotta", 8, 8, 1, '\uE4A0'),
    CYAN_WOOL(Material.CYAN_WOOL, "minecraft:block/cyan_wool", 8, 8, 1, '\uE4A1'),
    DAMAGED_ANVIL(Material.DAMAGED_ANVIL, "minecraft:block/damaged_anvil_top", 8, 8, 1, '\uE6FF'),
    DANDELION(Material.DANDELION, "minecraft:block/dandelion", 8, 8, 1, '\uE4A2'),
    DARK_OAK_BOAT(Material.DARK_OAK_BOAT, "minecraft:item/dark_oak_boat", 8, 8, 1, '\uE4A3'),
    DARK_OAK_DOOR(Material.DARK_OAK_DOOR, "minecraft:item/dark_oak_door", 8, 8, 1, '\uE4A4'),
    DARK_OAK_LEAVES(Material.DARK_OAK_LEAVES, "minecraft:block/dark_oak_leaves", 8, 8, 1, '\uE4A5'),
    DARK_OAK_LOG(Material.DARK_OAK_LOG, "minecraft:block/dark_oak_log", 8, 8, 1, '\uE4A6'),
    DARK_OAK_PLANKS(Material.DARK_OAK_PLANKS, "minecraft:block/dark_oak_planks", 8, 8, 1, '\uE4A7'),
    DARK_OAK_SAPLING(Material.DARK_OAK_SAPLING, "minecraft:block/dark_oak_sapling", 8, 8, 1, '\uE4A8'),
    DARK_OAK_SIGN(Material.DARK_OAK_SIGN, "minecraft:item/dark_oak_sign", 8, 8, 1, '\uE4A9'),
    DARK_OAK_TRAPDOOR(Material.DARK_OAK_TRAPDOOR, "minecraft:block/dark_oak_trapdoor", 8, 8, 1, '\uE4AA'),
    DARK_PRISMARINE(Material.DARK_PRISMARINE, "minecraft:block/dark_prismarine", 8, 8, 1, '\uE4AB'),
    DAYLIGHT_DETECTOR(Material.DAYLIGHT_DETECTOR, "minecraft:block/daylight_detector_side", 8, 8, 1, '\uE4AC'),
    DEAD_BRAIN_CORAL(Material.DEAD_BRAIN_CORAL, "minecraft:block/dead_brain_coral", 8, 8, 1, '\uE4AD'),
    DEAD_BRAIN_CORAL_BLOCK(Material.DEAD_BRAIN_CORAL_BLOCK, "minecraft:block/dead_brain_coral_block", 8, 8, 1, '\uE4AE'),
    DEAD_BRAIN_CORAL_FAN(Material.DEAD_BRAIN_CORAL_FAN, "minecraft:block/dead_brain_coral_fan", 8, 8, 1, '\uE4AF'),
    DEAD_BUBBLE_CORAL(Material.DEAD_BUBBLE_CORAL, "minecraft:block/dead_bubble_coral", 8, 8, 1, '\uE4B0'),
    DEAD_BUBBLE_CORAL_BLOCK(Material.DEAD_BUBBLE_CORAL_BLOCK, "minecraft:block/dead_bubble_coral_block", 8, 8, 1, '\uE4B1'),
    DEAD_BUBBLE_CORAL_FAN(Material.DEAD_BUBBLE_CORAL_FAN, "minecraft:block/dead_bubble_coral_fan", 8, 8, 1, '\uE4B2'),
    DEAD_BUSH(Material.DEAD_BUSH, "minecraft:block/dead_bush", 8, 8, 1, '\uE4B3'),
    DEAD_FIRE_CORAL(Material.DEAD_FIRE_CORAL, "minecraft:block/dead_fire_coral", 8, 8, 1, '\uE4B4'),
    DEAD_FIRE_CORAL_BLOCK(Material.DEAD_FIRE_CORAL_BLOCK, "minecraft:block/dead_fire_coral_block", 8, 8, 1, '\uE4B5'),
    DEAD_FIRE_CORAL_FAN(Material.DEAD_FIRE_CORAL_FAN, "minecraft:block/dead_fire_coral_fan", 8, 8, 1, '\uE4B6'),
    DEAD_HORN_CORAL(Material.DEAD_HORN_CORAL, "minecraft:block/dead_horn_coral", 8, 8, 1, '\uE4B7'),
    DEAD_HORN_CORAL_BLOCK(Material.DEAD_HORN_CORAL_BLOCK, "minecraft:block/dead_horn_coral_block", 8, 8, 1, '\uE4B8'),
    DEAD_HORN_CORAL_FAN(Material.DEAD_HORN_CORAL_FAN, "minecraft:block/dead_horn_coral_fan", 8, 8, 1, '\uE4B9'),
    DEAD_TUBE_CORAL(Material.DEAD_TUBE_CORAL, "minecraft:block/dead_tube_coral", 8, 8, 1, '\uE4BA'),
    DEAD_TUBE_CORAL_BLOCK(Material.DEAD_TUBE_CORAL_BLOCK, "minecraft:block/dead_tube_coral_block", 8, 8, 1, '\uE4BB'),
    DEAD_TUBE_CORAL_FAN(Material.DEAD_TUBE_CORAL_FAN, "minecraft:block/dead_tube_coral_fan", 8, 8, 1, '\uE4BC'),
    DEEPSLATE(Material.DEEPSLATE, "minecraft:block/deepslate", 8, 8, 1, '\uE6AB'),
    DEEPSLATE_BRICKS(Material.DEEPSLATE_BRICKS, "minecraft:block/deepslate_bricks", 8, 8, 1, '\uE6AC'),
    DEEPSLATE_COAL_ORE(Material.DEEPSLATE_COAL_ORE, "minecraft:block/deepslate_coal_ore", 8, 8, 1, '\uE6AD'),
    DEEPSLATE_COPPER_ORE(Material.DEEPSLATE_COPPER_ORE, "minecraft:block/deepslate_copper_ore", 8, 8, 1, '\uE6AE'),
    DEEPSLATE_DIAMOND_ORE(Material.DEEPSLATE_DIAMOND_ORE, "minecraft:block/deepslate_diamond_ore", 8, 8, 1, '\uE6AF'),
    DEEPSLATE_EMERALD_ORE(Material.DEEPSLATE_EMERALD_ORE, "minecraft:block/deepslate_emerald_ore", 8, 8, 1, '\uE6B0'),
    DEEPSLATE_GOLD_ORE(Material.DEEPSLATE_GOLD_ORE, "minecraft:block/deepslate_gold_ore", 8, 8, 1, '\uE6B1'),
    DEEPSLATE_IRON_ORE(Material.DEEPSLATE_IRON_ORE, "minecraft:block/deepslate_iron_ore", 8, 8, 1, '\uE6B2'),
    DEEPSLATE_LAPIS_ORE(Material.DEEPSLATE_LAPIS_ORE, "minecraft:block/deepslate_lapis_ore", 8, 8, 1, '\uE6B3'),
    DEEPSLATE_REDSTONE_ORE(Material.DEEPSLATE_REDSTONE_ORE, "minecraft:block/deepslate_redstone_ore", 8, 8, 1, '\uE6B4'),
    DEEPSLATE_TILES(Material.DEEPSLATE_TILES, "minecraft:block/deepslate_tiles", 8, 8, 1, '\uE6B5'),
    DETECTOR_RAIL(Material.DETECTOR_RAIL, "minecraft:block/detector_rail", 8, 8, 1, '\uE4BD'),
    DIAMOND(Material.DIAMOND, "minecraft:item/diamond", 8, 8, 1, '\uE4BE'),
    DIAMOND_AXE(Material.DIAMOND_AXE, "minecraft:item/diamond_axe", 8, 8, 1, '\uE4BF'),
    DIAMOND_BLOCK(Material.DIAMOND_BLOCK, "minecraft:block/diamond_block", 8, 8, 1, '\uE4C0'),
    DIAMOND_BOOTS(Material.DIAMOND_BOOTS, "minecraft:item/diamond_boots", 8, 8, 1, '\uE4C1'),
    DIAMOND_CHESTPLATE(Material.DIAMOND_CHESTPLATE, "minecraft:item/diamond_chestplate", 8, 8, 1, '\uE4C2'),
    DIAMOND_HELMET(Material.DIAMOND_HELMET, "minecraft:item/diamond_helmet", 8, 8, 1, '\uE4C3'),
    DIAMOND_HOE(Material.DIAMOND_HOE, "minecraft:item/diamond_hoe", 8, 8, 1, '\uE4C4'),
    DIAMOND_HORSE_ARMOR(Material.DIAMOND_HORSE_ARMOR, "minecraft:item/diamond_horse_armor", 8, 8, 1, '\uE4C5'),
    DIAMOND_LEGGINGS(Material.DIAMOND_LEGGINGS, "minecraft:item/diamond_leggings", 8, 8, 1, '\uE4C6'),
    DIAMOND_ORE(Material.DIAMOND_ORE, "minecraft:block/diamond_ore", 8, 8, 1, '\uE4C7'),
    DIAMOND_PICKAXE(Material.DIAMOND_PICKAXE, "minecraft:item/diamond_pickaxe", 8, 8, 1, '\uE4C8'),
    DIAMOND_SHOVEL(Material.DIAMOND_SHOVEL, "minecraft:item/diamond_shovel", 8, 8, 1, '\uE4C9'),
    DIAMOND_SWORD(Material.DIAMOND_SWORD, "minecraft:item/diamond_sword", 8, 8, 1, '\uE4CA'),
    DIORITE(Material.DIORITE, "minecraft:block/diorite", 8, 8, 1, '\uE4CB'),
    DIRT(Material.DIRT, "minecraft:block/dirt", 8, 8, 1, '\uE4CC'),
    DIRT_PATH(Material.DIRT_PATH, "minecraft:block/dirt_path_side", 8, 8, 1, '\uE50D'),
    DISPENSER(Material.DISPENSER, "minecraft:block/dispenser_front", 8, 8, 1, '\uE717'),
    DRAGON_BREATH(Material.DRAGON_BREATH, "minecraft:item/dragon_breath", 8, 8, 1, '\uE4CD'),
    DRAGON_EGG(Material.DRAGON_EGG, "minecraft:block/dragon_egg", 8, 8, 1, '\uE4CE'),
    DRIED_KELP(Material.DRIED_KELP, "minecraft:item/dried_kelp", 8, 8, 1, '\uE4CF'),
    DRIED_KELP_BLOCK(Material.DRIED_KELP_BLOCK, "minecraft:block/dried_kelp_top", 8, 8, 1, '\uE715'),
    DRIPSTONE_BLOCK(Material.DRIPSTONE_BLOCK, "minecraft:block/dripstone_block", 8, 8, 1, '\uE6B6'),
    DROPPER(Material.DROPPER, "minecraft:block/dropper_front", 8, 8, 1, '\uE718'),
    EGG(Material.EGG, "minecraft:item/egg", 8, 8, 1, '\uE4D0'),
    ELYTRA(Material.ELYTRA, "minecraft:item/elytra", 8, 8, 1, '\uE4D1'),
    EMERALD(Material.EMERALD, "minecraft:item/emerald", 8, 8, 1, '\uE4D2'),
    EMERALD_BLOCK(Material.EMERALD_BLOCK, "minecraft:block/emerald_block", 8, 8, 1, '\uE4D3'),
    EMERALD_ORE(Material.EMERALD_ORE, "minecraft:block/emerald_ore", 8, 8, 1, '\uE4D4'),
    ENCHANTED_BOOK(Material.ENCHANTED_BOOK, "minecraft:item/enchanted_book", 8, 8, 1, '\uE4D5'),
    ENCHANTING_TABLE(Material.ENCHANTING_TABLE, "minecraft:block/enchanting_table_side", 8, 8, 1, '\uE4D6'),
    ENDER_EYE(Material.ENDER_EYE, "minecraft:item/ender_eye", 8, 8, 1, '\uE4D7'),
    ENDER_PEARL(Material.ENDER_PEARL, "minecraft:item/ender_pearl", 8, 8, 1, '\uE4D8'),
    END_CRYSTAL(Material.END_CRYSTAL, "minecraft:item/end_crystal", 8, 8, 1, '\uE4D9'),
    END_PORTAL_FRAME(Material.END_PORTAL_FRAME, "minecraft:block/end_portal_frame_side", 8, 8, 1, '\uE4DA'),
    END_ROD(Material.END_ROD, "minecraft:block/end_rod", 8, 8, 1, '\uE4DB'),
    END_STONE(Material.END_STONE, "minecraft:block/end_stone", 8, 8, 1, '\uE4DC'),
    END_STONE_BRICKS(Material.END_STONE_BRICKS, "minecraft:block/end_stone_bricks", 8, 8, 1, '\uE4DD'),
    EXPERIENCE_BOTTLE(Material.EXPERIENCE_BOTTLE, "minecraft:item/experience_bottle", 8, 8, 1, '\uE4DE'),
    EXPOSED_COPPER(Material.EXPOSED_COPPER, "minecraft:block/exposed_copper", 8, 8, 1, '\uE6B7'),
    EXPOSED_CUT_COPPER(Material.EXPOSED_CUT_COPPER, "minecraft:block/exposed_cut_copper", 8, 8, 1, '\uE6B8'),
    FARMLAND(Material.FARMLAND, "minecraft:block/farmland", 8, 8, 1, '\uE4DF'),
    FEATHER(Material.FEATHER, "minecraft:item/feather", 8, 8, 1, '\uE4E0'),
    FERMENTED_SPIDER_EYE(Material.FERMENTED_SPIDER_EYE, "minecraft:item/fermented_spider_eye", 8, 8, 1, '\uE4E1'),
    FERN(Material.FERN, "minecraft:block/fern", 8, 8, 1, '\uE4E2'),
    FILLED_MAP(Material.FILLED_MAP, "minecraft:item/filled_map", 8, 8, 1, '\uE4E3'),
    FIREWORK_ROCKET(Material.FIREWORK_ROCKET, "minecraft:item/firework_rocket", 8, 8, 1, '\uE4E4'),
    FIREWORK_STAR(Material.FIREWORK_STAR, "minecraft:item/firework_star", 8, 8, 1, '\uE4E5'),
    FIRE_CHARGE(Material.FIRE_CHARGE, "minecraft:item/fire_charge", 8, 8, 1, '\uE4E6'),
    FIRE_CORAL(Material.FIRE_CORAL, "minecraft:block/fire_coral", 8, 8, 1, '\uE4E7'),
    FIRE_CORAL_BLOCK(Material.FIRE_CORAL_BLOCK, "minecraft:block/fire_coral_block", 8, 8, 1, '\uE4E8'),
    FIRE_CORAL_FAN(Material.FIRE_CORAL_FAN, "minecraft:block/fire_coral_fan", 8, 8, 1, '\uE4E9'),
    FISHING_ROD(Material.FISHING_ROD, "minecraft:item/fishing_rod", 8, 8, 1, '\uE4EA'),
    FLETCHING_TABLE(Material.FLETCHING_TABLE, "minecraft:block/fletching_table_front", 8, 8, 1, '\uE4EB'),
    FLINT(Material.FLINT, "minecraft:item/flint", 8, 8, 1, '\uE4EC'),
    FLINT_AND_STEEL(Material.FLINT_AND_STEEL, "minecraft:item/flint_and_steel", 8, 8, 1, '\uE4ED'),
    FLOWERING_AZALEA(Material.FLOWERING_AZALEA, "minecraft:block/flowering_azalea_side", 8, 8, 1, '\uE6B9'),
    FLOWERING_AZALEA_LEAVES(Material.FLOWERING_AZALEA_LEAVES, "minecraft:block/flowering_azalea_leaves", 8, 8, 1, '\uE6BA'),
    FLOWER_BANNER_PATTERN(Material.FLOWER_BANNER_PATTERN, "minecraft:item/flower_banner_pattern", 8, 8, 1, '\uE4EE'),
    FLOWER_POT(Material.FLOWER_POT, "minecraft:item/flower_pot", 8, 8, 1, '\uE4EF'),
    FURNACE(Material.FURNACE, "minecraft:block/furnace_front", 8, 8, 1, '\uE4F0'),
    FURNACE_MINECART(Material.FURNACE_MINECART, "minecraft:item/furnace_minecart", 8, 8, 1, '\uE4F1'),
    GHAST_TEAR(Material.GHAST_TEAR, "minecraft:item/ghast_tear", 8, 8, 1, '\uE4F2'),
    GILDED_BLACKSTONE(Material.GILDED_BLACKSTONE, "minecraft:block/gilded_blackstone", 8, 8, 1, '\uE4F3'),
    GLASS(Material.GLASS, "minecraft:block/glass", 8, 8, 1, '\uE4F4'),
    GLASS_BOTTLE(Material.GLASS_BOTTLE, "minecraft:item/glass_bottle", 8, 8, 1, '\uE4F5'),
    GLASS_PANE(Material.GLASS_PANE, "minecraft:block/glass_pane_top", 8, 8, 1, '\uE700'),
    GLISTERING_MELON_SLICE(Material.GLISTERING_MELON_SLICE, "minecraft:item/glistering_melon_slice", 8, 8, 1, '\uE4F6'),
    GLOBE_BANNER_PATTERN(Material.GLOBE_BANNER_PATTERN, "minecraft:item/globe_banner_pattern", 8, 8, 1, '\uE4F7'),
    GLOWSTONE(Material.GLOWSTONE, "minecraft:block/glowstone", 8, 8, 1, '\uE4F8'),
    GLOWSTONE_DUST(Material.GLOWSTONE_DUST, "minecraft:item/glowstone_dust", 8, 8, 1, '\uE4F9'),
    GLOW_BERRIES(Material.GLOW_BERRIES, "minecraft:item/glow_berries", 8, 8, 1, '\uE6BB'),
    GLOW_INK_SAC(Material.GLOW_INK_SAC, "minecraft:item/glow_ink_sac", 8, 8, 1, '\uE6BC'),
    GLOW_ITEM_FRAME(Material.GLOW_ITEM_FRAME, "minecraft:item/glow_item_frame", 8, 8, 1, '\uE6BD'),
    GLOW_LICHEN(Material.GLOW_LICHEN, "minecraft:block/glow_lichen", 8, 8, 1, '\uE6BE'),
    GOLDEN_APPLE(Material.GOLDEN_APPLE, "minecraft:item/golden_apple", 8, 8, 1, '\uE4FA'),
    GOLDEN_AXE(Material.GOLDEN_AXE, "minecraft:item/golden_axe", 8, 8, 1, '\uE4FB'),
    GOLDEN_BOOTS(Material.GOLDEN_BOOTS, "minecraft:item/golden_boots", 8, 8, 1, '\uE4FC'),
    GOLDEN_CARROT(Material.GOLDEN_CARROT, "minecraft:item/golden_carrot", 8, 8, 1, '\uE4FD'),
    GOLDEN_CHESTPLATE(Material.GOLDEN_CHESTPLATE, "minecraft:item/golden_chestplate", 8, 8, 1, '\uE4FE'),
    GOLDEN_HELMET(Material.GOLDEN_HELMET, "minecraft:item/golden_helmet", 8, 8, 1, '\uE4FF'),
    GOLDEN_HOE(Material.GOLDEN_HOE, "minecraft:item/golden_hoe", 8, 8, 1, '\uE500'),
    GOLDEN_HORSE_ARMOR(Material.GOLDEN_HORSE_ARMOR, "minecraft:item/golden_horse_armor", 8, 8, 1, '\uE501'),
    GOLDEN_LEGGINGS(Material.GOLDEN_LEGGINGS, "minecraft:item/golden_leggings", 8, 8, 1, '\uE502'),
    GOLDEN_PICKAXE(Material.GOLDEN_PICKAXE, "minecraft:item/golden_pickaxe", 8, 8, 1, '\uE503'),
    GOLDEN_SHOVEL(Material.GOLDEN_SHOVEL, "minecraft:item/golden_shovel", 8, 8, 1, '\uE504'),
    GOLDEN_SWORD(Material.GOLDEN_SWORD, "minecraft:item/golden_sword", 8, 8, 1, '\uE505'),
    GOLD_BLOCK(Material.GOLD_BLOCK, "minecraft:block/gold_block", 8, 8, 1, '\uE506'),
    GOLD_INGOT(Material.GOLD_INGOT, "minecraft:item/gold_ingot", 8, 8, 1, '\uE507'),
    GOLD_NUGGET(Material.GOLD_NUGGET, "minecraft:item/gold_nugget", 8, 8, 1, '\uE508'),
    GOLD_ORE(Material.GOLD_ORE, "minecraft:block/gold_ore", 8, 8, 1, '\uE509'),
    GRANITE(Material.GRANITE, "minecraft:block/granite", 8, 8, 1, '\uE50A'),
    GRASS(Material.GRASS, "minecraft:block/grass", 8, 8, 1, '\uE50B'),
    GRASS_BLOCK(Material.GRASS_BLOCK, "minecraft:block/grass_block_side", 8, 8, 1, '\uE50C'),
    GRAVEL(Material.GRAVEL, "minecraft:block/gravel", 8, 8, 1, '\uE50E'),
    GRAY_CANDLE(Material.GRAY_CANDLE, "minecraft:item/gray_candle", 8, 8, 1, '\uE6BF'),
    GRAY_CONCRETE(Material.GRAY_CONCRETE, "minecraft:block/gray_concrete", 8, 8, 1, '\uE50F'),
    GRAY_CONCRETE_POWDER(Material.GRAY_CONCRETE_POWDER, "minecraft:block/gray_concrete_powder", 8, 8, 1, '\uE510'),
    GRAY_DYE(Material.GRAY_DYE, "minecraft:item/gray_dye", 8, 8, 1, '\uE511'),
    GRAY_GLAZED_TERRACOTTA(Material.GRAY_GLAZED_TERRACOTTA, "minecraft:block/gray_glazed_terracotta", 8, 8, 1, '\uE512'),
    GRAY_SHULKER_BOX(Material.GRAY_SHULKER_BOX, "minecraft:block/gray_shulker_box", 8, 8, 1, '\uE513'),
    GRAY_STAINED_GLASS(Material.GRAY_STAINED_GLASS, "minecraft:block/gray_stained_glass", 8, 8, 1, '\uE514'),
    GRAY_STAINED_GLASS_PANE(Material.GRAY_STAINED_GLASS_PANE, "minecraft:block/gray_stained_glass_pane_top", 8, 8, 1, '\uE701'),
    GRAY_TERRACOTTA(Material.GRAY_TERRACOTTA, "minecraft:block/gray_terracotta", 8, 8, 1, '\uE515'),
    GRAY_WOOL(Material.GRAY_WOOL, "minecraft:block/gray_wool", 8, 8, 1, '\uE516'),
    GREEN_CANDLE(Material.GREEN_CANDLE, "minecraft:item/green_candle", 8, 8, 1, '\uE6C0'),
    GREEN_CONCRETE(Material.GREEN_CONCRETE, "minecraft:block/green_concrete", 8, 8, 1, '\uE517'),
    GREEN_CONCRETE_POWDER(Material.GREEN_CONCRETE_POWDER, "minecraft:block/green_concrete_powder", 8, 8, 1, '\uE518'),
    GREEN_DYE(Material.GREEN_DYE, "minecraft:item/green_dye", 8, 8, 1, '\uE519'),
    GREEN_GLAZED_TERRACOTTA(Material.GREEN_GLAZED_TERRACOTTA, "minecraft:block/green_glazed_terracotta", 8, 8, 1, '\uE51A'),
    GREEN_SHULKER_BOX(Material.GREEN_SHULKER_BOX, "minecraft:block/green_shulker_box", 8, 8, 1, '\uE51B'),
    GREEN_STAINED_GLASS(Material.GREEN_STAINED_GLASS, "minecraft:block/green_stained_glass", 8, 8, 1, '\uE51C'),
    GREEN_STAINED_GLASS_PANE(Material.GREEN_STAINED_GLASS_PANE, "minecraft:block/green_stained_glass_pane_top", 8, 8, 1, '\uE702'),
    GREEN_TERRACOTTA(Material.GREEN_TERRACOTTA, "minecraft:block/green_terracotta", 8, 8, 1, '\uE51D'),
    GREEN_WOOL(Material.GREEN_WOOL, "minecraft:block/green_wool", 8, 8, 1, '\uE51E'),
    GRINDSTONE(Material.GRINDSTONE, "minecraft:block/grindstone_side", 8, 8, 1, '\uE51F'),
    GUNPOWDER(Material.GUNPOWDER, "minecraft:item/gunpowder", 8, 8, 1, '\uE520'),
    HANGING_ROOTS(Material.HANGING_ROOTS, "minecraft:block/hanging_roots", 8, 8, 1, '\uE6C1'),
    HAY_BLOCK(Material.HAY_BLOCK, "minecraft:block/hay_block_side", 8, 8, 1, '\uE521'),
    HEART_OF_THE_SEA(Material.HEART_OF_THE_SEA, "minecraft:item/heart_of_the_sea", 8, 8, 1, '\uE522'),
    HONEYCOMB(Material.HONEYCOMB, "minecraft:item/honeycomb", 8, 8, 1, '\uE523'),
    HONEYCOMB_BLOCK(Material.HONEYCOMB_BLOCK, "minecraft:block/honeycomb_block", 8, 8, 1, '\uE524'),
    HONEY_BLOCK(Material.HONEY_BLOCK, "minecraft:block/honey_block_side", 8, 8, 1, '\uE525'),
    HONEY_BOTTLE(Material.HONEY_BOTTLE, "minecraft:item/honey_bottle", 8, 8, 1, '\uE526'),
    HOPPER(Material.HOPPER, "minecraft:item/hopper", 8, 8, 1, '\uE527'),
    HOPPER_MINECART(Material.HOPPER_MINECART, "minecraft:item/hopper_minecart", 8, 8, 1, '\uE528'),
    HORN_CORAL(Material.HORN_CORAL, "minecraft:block/horn_coral", 8, 8, 1, '\uE529'),
    HORN_CORAL_BLOCK(Material.HORN_CORAL_BLOCK, "minecraft:block/horn_coral_block", 8, 8, 1, '\uE52A'),
    HORN_CORAL_FAN(Material.HORN_CORAL_FAN, "minecraft:block/horn_coral_fan", 8, 8, 1, '\uE52B'),
    ICE(Material.ICE, "minecraft:block/ice", 8, 8, 1, '\uE52C'),
    INK_SAC(Material.INK_SAC, "minecraft:item/ink_sac", 8, 8, 1, '\uE52D'),
    IRON_AXE(Material.IRON_AXE, "minecraft:item/iron_axe", 8, 8, 1, '\uE52E'),
    IRON_BARS(Material.IRON_BARS, "minecraft:block/iron_bars", 8, 8, 1, '\uE52F'),
    IRON_BLOCK(Material.IRON_BLOCK, "minecraft:block/iron_block", 8, 8, 1, '\uE530'),
    IRON_BOOTS(Material.IRON_BOOTS, "minecraft:item/iron_boots", 8, 8, 1, '\uE531'),
    IRON_CHESTPLATE(Material.IRON_CHESTPLATE, "minecraft:item/iron_chestplate", 8, 8, 1, '\uE532'),
    IRON_DOOR(Material.IRON_DOOR, "minecraft:item/iron_door", 8, 8, 1, '\uE533'),
    IRON_HELMET(Material.IRON_HELMET, "minecraft:item/iron_helmet", 8, 8, 1, '\uE534'),
    IRON_HOE(Material.IRON_HOE, "minecraft:item/iron_hoe", 8, 8, 1, '\uE535'),
    IRON_HORSE_ARMOR(Material.IRON_HORSE_ARMOR, "minecraft:item/iron_horse_armor", 8, 8, 1, '\uE536'),
    IRON_INGOT(Material.IRON_INGOT, "minecraft:item/iron_ingot", 8, 8, 1, '\uE537'),
    IRON_LEGGINGS(Material.IRON_LEGGINGS, "minecraft:item/iron_leggings", 8, 8, 1, '\uE538'),
    IRON_NUGGET(Material.IRON_NUGGET, "minecraft:item/iron_nugget", 8, 8, 1, '\uE539'),
    IRON_ORE(Material.IRON_ORE, "minecraft:block/iron_ore", 8, 8, 1, '\uE53A'),
    IRON_PICKAXE(Material.IRON_PICKAXE, "minecraft:item/iron_pickaxe", 8, 8, 1, '\uE53B'),
    IRON_SHOVEL(Material.IRON_SHOVEL, "minecraft:item/iron_shovel", 8, 8, 1, '\uE53C'),
    IRON_SWORD(Material.IRON_SWORD, "minecraft:item/iron_sword", 8, 8, 1, '\uE53D'),
    IRON_TRAPDOOR(Material.IRON_TRAPDOOR, "minecraft:block/iron_trapdoor", 8, 8, 1, '\uE53E'),
    ITEM_FRAME(Material.ITEM_FRAME, "minecraft:item/item_frame", 8, 8, 1, '\uE53F'),
    JACK_O_LANTERN(Material.JACK_O_LANTERN, "minecraft:block/jack_o_lantern", 8, 8, 1, '\uE540'),
    JIGSAW(Material.JIGSAW, "minecraft:block/jigsaw_side", 8, 8, 1, '\uE541'),
    JUKEBOX(Material.JUKEBOX, "minecraft:block/jukebox_side", 8, 8, 1, '\uE542'),
    JUNGLE_BOAT(Material.JUNGLE_BOAT, "minecraft:item/jungle_boat", 8, 8, 1, '\uE543'),
    JUNGLE_DOOR(Material.JUNGLE_DOOR, "minecraft:item/jungle_door", 8, 8, 1, '\uE544'),
    JUNGLE_LEAVES(Material.JUNGLE_LEAVES, "minecraft:block/jungle_leaves", 8, 8, 1, '\uE545'),
    JUNGLE_LOG(Material.JUNGLE_LOG, "minecraft:block/jungle_log", 8, 8, 1, '\uE546'),
    JUNGLE_PLANKS(Material.JUNGLE_PLANKS, "minecraft:block/jungle_planks", 8, 8, 1, '\uE547'),
    JUNGLE_SAPLING(Material.JUNGLE_SAPLING, "minecraft:block/jungle_sapling", 8, 8, 1, '\uE548'),
    JUNGLE_SIGN(Material.JUNGLE_SIGN, "minecraft:item/jungle_sign", 8, 8, 1, '\uE549'),
    JUNGLE_TRAPDOOR(Material.JUNGLE_TRAPDOOR, "minecraft:block/jungle_trapdoor", 8, 8, 1, '\uE54A'),
    KELP(Material.KELP, "minecraft:item/kelp", 8, 8, 1, '\uE54B'),
    KNOWLEDGE_BOOK(Material.KNOWLEDGE_BOOK, "minecraft:item/knowledge_book", 8, 8, 1, '\uE54C'),
    LADDER(Material.LADDER, "minecraft:block/ladder", 8, 8, 1, '\uE54D'),
    LANTERN(Material.LANTERN, "minecraft:item/lantern", 8, 8, 1, '\uE54E'),
    LAPIS_BLOCK(Material.LAPIS_BLOCK, "minecraft:block/lapis_block", 8, 8, 1, '\uE54F'),
    LAPIS_LAZULI(Material.LAPIS_LAZULI, "minecraft:item/lapis_lazuli", 8, 8, 1, '\uE550'),
    LAPIS_ORE(Material.LAPIS_ORE, "minecraft:block/lapis_ore", 8, 8, 1, '\uE551'),
    LARGE_AMETHYST_BUD(Material.LARGE_AMETHYST_BUD, "minecraft:block/large_amethyst_bud", 8, 8, 1, '\uE6C2'),
    LARGE_FERN(Material.LARGE_FERN, "minecraft:block/large_fern_top", 8, 8, 1, '\uE703'),
    LAVA_BUCKET(Material.LAVA_BUCKET, "minecraft:item/lava_bucket", 8, 8, 1, '\uE552'),
    LEAD(Material.LEAD, "minecraft:item/lead", 8, 8, 1, '\uE553'),
    LEATHER(Material.LEATHER, "minecraft:item/leather", 8, 8, 1, '\uE554'),
    LEATHER_BOOTS(Material.LEATHER_BOOTS, "minecraft:item/leather_boots", 8, 8, 1, '\uE555'),
    LEATHER_CHESTPLATE(Material.LEATHER_CHESTPLATE, "minecraft:item/leather_chestplate", 8, 8, 1, '\uE556'),
    LEATHER_HELMET(Material.LEATHER_HELMET, "minecraft:item/leather_helmet", 8, 8, 1, '\uE557'),
    LEATHER_HORSE_ARMOR(Material.LEATHER_HORSE_ARMOR, "minecraft:item/leather_horse_armor", 8, 8, 1, '\uE558'),
    LEATHER_LEGGINGS(Material.LEATHER_LEGGINGS, "minecraft:item/leather_leggings", 8, 8, 1, '\uE559'),
    LECTERN(Material.LECTERN, "minecraft:block/lectern_top", 8, 8, 1, '\uE704'),
    LEVER(Material.LEVER, "minecraft:block/lever", 8, 8, 1, '\uE55A'),
    LIGHT(Material.LIGHT, "minecraft:item/light", 8, 8, 1, '\uE6C3'),
    LIGHTNING_ROD(Material.LIGHTNING_ROD, "minecraft:block/lightning_rod", 8, 8, 1, '\uE6C4'),
    LIGHT_BLUE_CANDLE(Material.LIGHT_BLUE_CANDLE, "minecraft:item/light_blue_candle", 8, 8, 1, '\uE6C5'),
    LIGHT_BLUE_CONCRETE(Material.LIGHT_BLUE_CONCRETE, "minecraft:block/light_blue_concrete", 8, 8, 1, '\uE55B'),
    LIGHT_BLUE_CONCRETE_POWDER(Material.LIGHT_BLUE_CONCRETE_POWDER, "minecraft:block/light_blue_concrete_powder", 8, 8, 1, '\uE55C'),
    LIGHT_BLUE_DYE(Material.LIGHT_BLUE_DYE, "minecraft:item/light_blue_dye", 8, 8, 1, '\uE55D'),
    LIGHT_BLUE_GLAZED_TERRACOTTA(Material.LIGHT_BLUE_GLAZED_TERRACOTTA, "minecraft:block/light_blue_glazed_terracotta", 8, 8, 1, '\uE55E'),
    LIGHT_BLUE_SHULKER_BOX(Material.LIGHT_BLUE_SHULKER_BOX, "minecraft:block/light_blue_shulker_box", 8, 8, 1, '\uE55F'),
    LIGHT_BLUE_STAINED_GLASS(Material.LIGHT_BLUE_STAINED_GLASS, "minecraft:block/light_blue_stained_glass", 8, 8, 1, '\uE560'),
    LIGHT_BLUE_STAINED_GLASS_PANE(Material.LIGHT_BLUE_STAINED_GLASS_PANE, "minecraft:block/light_blue_stained_glass_pane_top", 8, 8, 1, '\uE705'),
    LIGHT_BLUE_TERRACOTTA(Material.LIGHT_BLUE_TERRACOTTA, "minecraft:block/light_blue_terracotta", 8, 8, 1, '\uE561'),
    LIGHT_BLUE_WOOL(Material.LIGHT_BLUE_WOOL, "minecraft:block/light_blue_wool", 8, 8, 1, '\uE562'),
    LIGHT_GRAY_CANDLE(Material.LIGHT_GRAY_CANDLE, "minecraft:item/light_gray_candle", 8, 8, 1, '\uE6C6'),
    LIGHT_GRAY_CONCRETE(Material.LIGHT_GRAY_CONCRETE, "minecraft:block/light_gray_concrete", 8, 8, 1, '\uE563'),
    LIGHT_GRAY_CONCRETE_POWDER(Material.LIGHT_GRAY_CONCRETE_POWDER, "minecraft:block/light_gray_concrete_powder", 8, 8, 1, '\uE564'),
    LIGHT_GRAY_DYE(Material.LIGHT_GRAY_DYE, "minecraft:item/light_gray_dye", 8, 8, 1, '\uE565'),
    LIGHT_GRAY_GLAZED_TERRACOTTA(Material.LIGHT_GRAY_GLAZED_TERRACOTTA, "minecraft:block/light_gray_glazed_terracotta", 8, 8, 1, '\uE566'),
    LIGHT_GRAY_SHULKER_BOX(Material.LIGHT_GRAY_SHULKER_BOX, "minecraft:block/light_gray_shulker_box", 8, 8, 1, '\uE567'),
    LIGHT_GRAY_STAINED_GLASS(Material.LIGHT_GRAY_STAINED_GLASS, "minecraft:block/light_gray_stained_glass", 8, 8, 1, '\uE568'),
    LIGHT_GRAY_STAINED_GLASS_PANE(Material.LIGHT_GRAY_STAINED_GLASS_PANE, "minecraft:block/light_gray_stained_glass_pane_top", 8, 8, 1, '\uE706'),
    LIGHT_GRAY_TERRACOTTA(Material.LIGHT_GRAY_TERRACOTTA, "minecraft:block/light_gray_terracotta", 8, 8, 1, '\uE569'),
    LIGHT_GRAY_WOOL(Material.LIGHT_GRAY_WOOL, "minecraft:block/light_gray_wool", 8, 8, 1, '\uE56A'),
    LILAC(Material.LILAC, "minecraft:block/lilac_top", 8, 8, 1, '\uE707'),
    LILY_OF_THE_VALLEY(Material.LILY_OF_THE_VALLEY, "minecraft:block/lily_of_the_valley", 8, 8, 1, '\uE56B'),
    LILY_PAD(Material.LILY_PAD, "minecraft:block/lily_pad", 8, 8, 1, '\uE56C'),
    LIME_CANDLE(Material.LIME_CANDLE, "minecraft:item/lime_candle", 8, 8, 1, '\uE6C7'),
    LIME_CONCRETE(Material.LIME_CONCRETE, "minecraft:block/lime_concrete", 8, 8, 1, '\uE56D'),
    LIME_CONCRETE_POWDER(Material.LIME_CONCRETE_POWDER, "minecraft:block/lime_concrete_powder", 8, 8, 1, '\uE56E'),
    LIME_DYE(Material.LIME_DYE, "minecraft:item/lime_dye", 8, 8, 1, '\uE56F'),
    LIME_GLAZED_TERRACOTTA(Material.LIME_GLAZED_TERRACOTTA, "minecraft:block/lime_glazed_terracotta", 8, 8, 1, '\uE570'),
    LIME_SHULKER_BOX(Material.LIME_SHULKER_BOX, "minecraft:block/lime_shulker_box", 8, 8, 1, '\uE571'),
    LIME_STAINED_GLASS(Material.LIME_STAINED_GLASS, "minecraft:block/lime_stained_glass", 8, 8, 1, '\uE572'),
    LIME_STAINED_GLASS_PANE(Material.LIME_STAINED_GLASS_PANE, "minecraft:block/lime_stained_glass_pane_top", 8, 8, 1, '\uE708'),
    LIME_TERRACOTTA(Material.LIME_TERRACOTTA, "minecraft:block/lime_terracotta", 8, 8, 1, '\uE573'),
    LIME_WOOL(Material.LIME_WOOL, "minecraft:block/lime_wool", 8, 8, 1, '\uE574'),
    LINGERING_POTION(Material.LINGERING_POTION, "minecraft:item/lingering_potion", 8, 8, 1, '\uE575'),
    LODESTONE(Material.LODESTONE, "minecraft:block/lodestone_side", 8, 8, 1, '\uE576'),
    LOOM(Material.LOOM, "minecraft:block/loom_front", 8, 8, 1, '\uE577'),
    MAGENTA_CANDLE(Material.MAGENTA_CANDLE, "minecraft:item/magenta_candle", 8, 8, 1, '\uE6C8'),
    MAGENTA_CONCRETE(Material.MAGENTA_CONCRETE, "minecraft:block/magenta_concrete", 8, 8, 1, '\uE578'),
    MAGENTA_CONCRETE_POWDER(Material.MAGENTA_CONCRETE_POWDER, "minecraft:block/magenta_concrete_powder", 8, 8, 1, '\uE579'),
    MAGENTA_DYE(Material.MAGENTA_DYE, "minecraft:item/magenta_dye", 8, 8, 1, '\uE57A'),
    MAGENTA_GLAZED_TERRACOTTA(Material.MAGENTA_GLAZED_TERRACOTTA, "minecraft:block/magenta_glazed_terracotta", 8, 8, 1, '\uE57B'),
    MAGENTA_SHULKER_BOX(Material.MAGENTA_SHULKER_BOX, "minecraft:block/magenta_shulker_box", 8, 8, 1, '\uE57C'),
    MAGENTA_STAINED_GLASS(Material.MAGENTA_STAINED_GLASS, "minecraft:block/magenta_stained_glass", 8, 8, 1, '\uE57D'),
    MAGENTA_STAINED_GLASS_PANE(Material.MAGENTA_STAINED_GLASS_PANE, "minecraft:block/magenta_stained_glass_pane_top", 8, 8, 1, '\uE709'),
    MAGENTA_TERRACOTTA(Material.MAGENTA_TERRACOTTA, "minecraft:block/magenta_terracotta", 8, 8, 1, '\uE57E'),
    MAGENTA_WOOL(Material.MAGENTA_WOOL, "minecraft:block/magenta_wool", 8, 8, 1, '\uE57F'),
    MAGMA_BLOCK(Material.MAGMA_BLOCK, "minecraft:block/magma", 8, 8, 3, '\uE716'),
    MAGMA_CREAM(Material.MAGMA_CREAM, "minecraft:item/magma_cream", 8, 8, 1, '\uE580'),
    MAP(Material.MAP, "minecraft:item/map", 8, 8, 1, '\uE581'),
    MEDIUM_AMETHYST_BUD(Material.MEDIUM_AMETHYST_BUD, "minecraft:block/medium_amethyst_bud", 8, 8, 1, '\uE6C9'),
    MELON(Material.MELON, "minecraft:block/melon_side", 8, 8, 1, '\uE582'),
    MELON_SEEDS(Material.MELON_SEEDS, "minecraft:item/melon_seeds", 8, 8, 1, '\uE583'),
    MELON_SLICE(Material.MELON_SLICE, "minecraft:item/melon_slice", 8, 8, 1, '\uE584'),
    MELON_STEM(Material.MELON_STEM, "minecraft:block/melon_stem", 8, 8, 1, '\uE585'),
    MILK_BUCKET(Material.MILK_BUCKET, "minecraft:item/milk_bucket", 8, 8, 1, '\uE586'),
    MINECART(Material.MINECART, "minecraft:item/minecart", 8, 8, 1, '\uE587'),
    MOJANG_BANNER_PATTERN(Material.MOJANG_BANNER_PATTERN, "minecraft:item/mojang_banner_pattern", 8, 8, 1, '\uE588'),
    MOSSY_COBBLESTONE(Material.MOSSY_COBBLESTONE, "minecraft:block/mossy_cobblestone", 8, 8, 1, '\uE589'),
    MOSSY_STONE_BRICKS(Material.MOSSY_STONE_BRICKS, "minecraft:block/mossy_stone_bricks", 8, 8, 1, '\uE58A'),
    MOSS_BLOCK(Material.MOSS_BLOCK, "minecraft:block/moss_block", 8, 8, 1, '\uE6CA'),
    MUSHROOM_STEM(Material.MUSHROOM_STEM, "minecraft:block/mushroom_stem", 8, 8, 1, '\uE58B'),
    MUSHROOM_STEW(Material.MUSHROOM_STEW, "minecraft:item/mushroom_stew", 8, 8, 1, '\uE58C'),
    MUSIC_DISC_11(Material.MUSIC_DISC_11, "minecraft:item/music_disc_11", 8, 8, 1, '\uE58D'),
    MUSIC_DISC_13(Material.MUSIC_DISC_13, "minecraft:item/music_disc_13", 8, 8, 1, '\uE58E'),
    MUSIC_DISC_BLOCKS(Material.MUSIC_DISC_BLOCKS, "minecraft:item/music_disc_blocks", 8, 8, 1, '\uE58F'),
    MUSIC_DISC_CAT(Material.MUSIC_DISC_CAT, "minecraft:item/music_disc_cat", 8, 8, 1, '\uE590'),
    MUSIC_DISC_CHIRP(Material.MUSIC_DISC_CHIRP, "minecraft:item/music_disc_chirp", 8, 8, 1, '\uE591'),
    MUSIC_DISC_FAR(Material.MUSIC_DISC_FAR, "minecraft:item/music_disc_far", 8, 8, 1, '\uE592'),
    MUSIC_DISC_MALL(Material.MUSIC_DISC_MALL, "minecraft:item/music_disc_mall", 8, 8, 1, '\uE593'),
    MUSIC_DISC_MELLOHI(Material.MUSIC_DISC_MELLOHI, "minecraft:item/music_disc_mellohi", 8, 8, 1, '\uE594'),
    MUSIC_DISC_OTHERSIDE(Material.MUSIC_DISC_OTHERSIDE, "minecraft:item/music_disc_otherside", 8, 8, 1, '\uE6F0'),
    MUSIC_DISC_PIGSTEP(Material.MUSIC_DISC_PIGSTEP, "minecraft:item/music_disc_pigstep", 8, 8, 1, '\uE595'),
    MUSIC_DISC_STAL(Material.MUSIC_DISC_STAL, "minecraft:item/music_disc_stal", 8, 8, 1, '\uE596'),
    MUSIC_DISC_STRAD(Material.MUSIC_DISC_STRAD, "minecraft:item/music_disc_strad", 8, 8, 1, '\uE597'),
    MUSIC_DISC_WAIT(Material.MUSIC_DISC_WAIT, "minecraft:item/music_disc_wait", 8, 8, 1, '\uE598'),
    MUSIC_DISC_WARD(Material.MUSIC_DISC_WARD, "minecraft:item/music_disc_ward", 8, 8, 1, '\uE599'),
    MUTTON(Material.MUTTON, "minecraft:item/mutton", 8, 8, 1, '\uE59A'),
    MYCELIUM(Material.MYCELIUM, "minecraft:block/mycelium_side", 8, 8, 1, '\uE59B'),
    NAME_TAG(Material.NAME_TAG, "minecraft:item/name_tag", 8, 8, 1, '\uE59C'),
    NAUTILUS_SHELL(Material.NAUTILUS_SHELL, "minecraft:item/nautilus_shell", 8, 8, 1, '\uE59D'),
    NETHERITE_AXE(Material.NETHERITE_AXE, "minecraft:item/netherite_axe", 8, 8, 1, '\uE59E'),
    NETHERITE_BLOCK(Material.NETHERITE_BLOCK, "minecraft:block/netherite_block", 8, 8, 1, '\uE59F'),
    NETHERITE_BOOTS(Material.NETHERITE_BOOTS, "minecraft:item/netherite_boots", 8, 8, 1, '\uE5A0'),
    NETHERITE_CHESTPLATE(Material.NETHERITE_CHESTPLATE, "minecraft:item/netherite_chestplate", 8, 8, 1, '\uE5A1'),
    NETHERITE_HELMET(Material.NETHERITE_HELMET, "minecraft:item/netherite_helmet", 8, 8, 1, '\uE5A2'),
    NETHERITE_HOE(Material.NETHERITE_HOE, "minecraft:item/netherite_hoe", 8, 8, 1, '\uE5A3'),
    NETHERITE_INGOT(Material.NETHERITE_INGOT, "minecraft:item/netherite_ingot", 8, 8, 1, '\uE5A4'),
    NETHERITE_LEGGINGS(Material.NETHERITE_LEGGINGS, "minecraft:item/netherite_leggings", 8, 8, 1, '\uE5A5'),
    NETHERITE_PICKAXE(Material.NETHERITE_PICKAXE, "minecraft:item/netherite_pickaxe", 8, 8, 1, '\uE5A6'),
    NETHERITE_SCRAP(Material.NETHERITE_SCRAP, "minecraft:item/netherite_scrap", 8, 8, 1, '\uE5A7'),
    NETHERITE_SHOVEL(Material.NETHERITE_SHOVEL, "minecraft:item/netherite_shovel", 8, 8, 1, '\uE5A8'),
    NETHERITE_SWORD(Material.NETHERITE_SWORD, "minecraft:item/netherite_sword", 8, 8, 1, '\uE5A9'),
    NETHERRACK(Material.NETHERRACK, "minecraft:block/netherrack", 8, 8, 1, '\uE5AA'),
    NETHER_BRICK(Material.NETHER_BRICK, "minecraft:item/nether_brick", 8, 8, 1, '\uE5AB'),
    NETHER_BRICKS(Material.NETHER_BRICKS, "minecraft:block/nether_bricks", 8, 8, 1, '\uE5AC'),
    NETHER_GOLD_ORE(Material.NETHER_GOLD_ORE, "minecraft:block/nether_gold_ore", 8, 8, 1, '\uE5AD'),
    NETHER_QUARTZ_ORE(Material.NETHER_QUARTZ_ORE, "minecraft:block/nether_quartz_ore", 8, 8, 1, '\uE5AE'),
    NETHER_SPROUTS(Material.NETHER_SPROUTS, "minecraft:item/nether_sprouts", 8, 8, 1, '\uE5AF'),
    NETHER_STAR(Material.NETHER_STAR, "minecraft:item/nether_star", 8, 8, 1, '\uE5B0'),
    NETHER_WART(Material.NETHER_WART, "minecraft:item/nether_wart", 8, 8, 1, '\uE5B1'),
    NETHER_WART_BLOCK(Material.NETHER_WART_BLOCK, "minecraft:block/nether_wart_block", 8, 8, 1, '\uE5B2'),
    NOTE_BLOCK(Material.NOTE_BLOCK, "minecraft:block/note_block", 8, 8, 1, '\uE5B3'),
    OAK_BOAT(Material.OAK_BOAT, "minecraft:item/oak_boat", 8, 8, 1, '\uE5B4'),
    OAK_DOOR(Material.OAK_DOOR, "minecraft:item/oak_door", 8, 8, 1, '\uE5B5'),
    OAK_LEAVES(Material.OAK_LEAVES, "minecraft:block/oak_leaves", 8, 8, 1, '\uE5B6'),
    OAK_LOG(Material.OAK_LOG, "minecraft:block/oak_log", 8, 8, 1, '\uE5B7'),
    OAK_PLANKS(Material.OAK_PLANKS, "minecraft:block/oak_planks", 8, 8, 1, '\uE5B8'),
    OAK_SAPLING(Material.OAK_SAPLING, "minecraft:block/oak_sapling", 8, 8, 1, '\uE5B9'),
    OAK_SIGN(Material.OAK_SIGN, "minecraft:item/oak_sign", 8, 8, 1, '\uE5BA'),
    OAK_TRAPDOOR(Material.OAK_TRAPDOOR, "minecraft:block/oak_trapdoor", 8, 8, 1, '\uE5BB'),
    OBSERVER(Material.OBSERVER, "minecraft:block/observer_front", 8, 8, 1, '\uE5BC'),
    OBSIDIAN(Material.OBSIDIAN, "minecraft:block/obsidian", 8, 8, 1, '\uE5BD'),
    ORANGE_CANDLE(Material.ORANGE_CANDLE, "minecraft:item/orange_candle", 8, 8, 1, '\uE6CB'),
    ORANGE_CONCRETE(Material.ORANGE_CONCRETE, "minecraft:block/orange_concrete", 8, 8, 1, '\uE5BE'),
    ORANGE_CONCRETE_POWDER(Material.ORANGE_CONCRETE_POWDER, "minecraft:block/orange_concrete_powder", 8, 8, 1, '\uE5BF'),
    ORANGE_DYE(Material.ORANGE_DYE, "minecraft:item/orange_dye", 8, 8, 1, '\uE5C0'),
    ORANGE_GLAZED_TERRACOTTA(Material.ORANGE_GLAZED_TERRACOTTA, "minecraft:block/orange_glazed_terracotta", 8, 8, 1, '\uE5C1'),
    ORANGE_SHULKER_BOX(Material.ORANGE_SHULKER_BOX, "minecraft:block/orange_shulker_box", 8, 8, 1, '\uE5C2'),
    ORANGE_STAINED_GLASS(Material.ORANGE_STAINED_GLASS, "minecraft:block/orange_stained_glass", 8, 8, 1, '\uE5C3'),
    ORANGE_STAINED_GLASS_PANE(Material.ORANGE_STAINED_GLASS_PANE, "minecraft:block/orange_stained_glass_pane_top", 8, 8, 1, '\uE70A'),
    ORANGE_TERRACOTTA(Material.ORANGE_TERRACOTTA, "minecraft:block/orange_terracotta", 8, 8, 1, '\uE5C4'),
    ORANGE_TULIP(Material.ORANGE_TULIP, "minecraft:block/orange_tulip", 8, 8, 1, '\uE5C5'),
    ORANGE_WOOL(Material.ORANGE_WOOL, "minecraft:block/orange_wool", 8, 8, 1, '\uE5C6'),
    OXEYE_DAISY(Material.OXEYE_DAISY, "minecraft:block/oxeye_daisy", 8, 8, 1, '\uE5C7'),
    OXIDIZED_COPPER(Material.OXIDIZED_COPPER, "minecraft:block/oxidized_copper", 8, 8, 1, '\uE6CC'),
    OXIDIZED_CUT_COPPER(Material.OXIDIZED_CUT_COPPER, "minecraft:block/oxidized_cut_copper", 8, 8, 1, '\uE6CD'),
    PACKED_ICE(Material.PACKED_ICE, "minecraft:block/packed_ice", 8, 8, 1, '\uE5C8'),
    PAINTING(Material.PAINTING, "minecraft:item/painting", 8, 8, 1, '\uE5C9'),
    PAPER(Material.PAPER, "minecraft:item/paper", 8, 8, 1, '\uE5CA'),
    PEONY(Material.PEONY, "minecraft:block/peony_top", 8, 8, 1, '\uE70B'),
    PHANTOM_MEMBRANE(Material.PHANTOM_MEMBRANE, "minecraft:item/phantom_membrane", 8, 8, 1, '\uE5CB'),
    PIGLIN_BANNER_PATTERN(Material.PIGLIN_BANNER_PATTERN, "minecraft:item/piglin_banner_pattern", 8, 8, 1, '\uE5CC'),
    PINK_CANDLE(Material.PINK_CANDLE, "minecraft:item/pink_candle", 8, 8, 1, '\uE6CE'),
    PINK_CONCRETE(Material.PINK_CONCRETE, "minecraft:block/pink_concrete", 8, 8, 1, '\uE5CD'),
    PINK_CONCRETE_POWDER(Material.PINK_CONCRETE_POWDER, "minecraft:block/pink_concrete_powder", 8, 8, 1, '\uE5CE'),
    PINK_DYE(Material.PINK_DYE, "minecraft:item/pink_dye", 8, 8, 1, '\uE5CF'),
    PINK_GLAZED_TERRACOTTA(Material.PINK_GLAZED_TERRACOTTA, "minecraft:block/pink_glazed_terracotta", 8, 8, 1, '\uE5D0'),
    PINK_SHULKER_BOX(Material.PINK_SHULKER_BOX, "minecraft:block/pink_shulker_box", 8, 8, 1, '\uE5D1'),
    PINK_STAINED_GLASS(Material.PINK_STAINED_GLASS, "minecraft:block/pink_stained_glass", 8, 8, 1, '\uE5D2'),
    PINK_STAINED_GLASS_PANE(Material.PINK_STAINED_GLASS_PANE, "minecraft:block/pink_stained_glass_pane_top", 8, 8, 1, '\uE70C'),
    PINK_TERRACOTTA(Material.PINK_TERRACOTTA, "minecraft:block/pink_terracotta", 8, 8, 1, '\uE5D3'),
    PINK_TULIP(Material.PINK_TULIP, "minecraft:block/pink_tulip", 8, 8, 1, '\uE5D4'),
    PINK_WOOL(Material.PINK_WOOL, "minecraft:block/pink_wool", 8, 8, 1, '\uE5D5'),
    PISTON(Material.PISTON, "minecraft:block/piston_side", 8, 8, 1, '\uE5D6'),
    PODZOL(Material.PODZOL, "minecraft:block/podzol_side", 8, 8, 1, '\uE5D7'),
    POINTED_DRIPSTONE(Material.POINTED_DRIPSTONE, "minecraft:item/pointed_dripstone", 8, 8, 1, '\uE6CF'),
    POISONOUS_POTATO(Material.POISONOUS_POTATO, "minecraft:item/poisonous_potato", 8, 8, 1, '\uE5D8'),
    POLISHED_ANDESITE(Material.POLISHED_ANDESITE, "minecraft:block/polished_andesite", 8, 8, 1, '\uE5D9'),
    POLISHED_BASALT(Material.POLISHED_BASALT, "minecraft:block/polished_basalt_side", 8, 8, 1, '\uE5DA'),
    POLISHED_BLACKSTONE(Material.POLISHED_BLACKSTONE, "minecraft:block/polished_blackstone", 8, 8, 1, '\uE5DB'),
    POLISHED_BLACKSTONE_BRICKS(Material.POLISHED_BLACKSTONE_BRICKS, "minecraft:block/polished_blackstone_bricks", 8, 8, 1, '\uE5DC'),
    POLISHED_DEEPSLATE(Material.POLISHED_DEEPSLATE, "minecraft:block/polished_deepslate", 8, 8, 1, '\uE6D0'),
    POLISHED_DIORITE(Material.POLISHED_DIORITE, "minecraft:block/polished_diorite", 8, 8, 1, '\uE5DD'),
    POLISHED_GRANITE(Material.POLISHED_GRANITE, "minecraft:block/polished_granite", 8, 8, 1, '\uE5DE'),
    POPPED_CHORUS_FRUIT(Material.POPPED_CHORUS_FRUIT, "minecraft:item/popped_chorus_fruit", 8, 8, 1, '\uE5DF'),
    POPPY(Material.POPPY, "minecraft:block/poppy", 8, 8, 1, '\uE5E0'),
    PORKCHOP(Material.PORKCHOP, "minecraft:item/porkchop", 8, 8, 1, '\uE5E1'),
    POTATO(Material.POTATO, "minecraft:item/potato", 8, 8, 1, '\uE5E2'),
    POTION(Material.POTION, "minecraft:item/potion", 8, 8, 1, '\uE5E3'),
    POTTED_AZALEA_BUSH(Material.POTTED_AZALEA_BUSH, "minecraft:block/potted_azalea_bush_side", 8, 8, 1, '\uE6D1'),
    POTTED_FLOWERING_AZALEA_BUSH(Material.POTTED_FLOWERING_AZALEA_BUSH, "minecraft:block/potted_flowering_azalea_bush_side", 8, 8, 1, '\uE6D2'),
    POWDER_SNOW(Material.POWDER_SNOW, "minecraft:block/powder_snow", 8, 8, 1, '\uE6D3'),
    POWDER_SNOW_BUCKET(Material.POWDER_SNOW_BUCKET, "minecraft:item/powder_snow_bucket", 8, 8, 1, '\uE6D4'),
    POWERED_RAIL(Material.POWERED_RAIL, "minecraft:block/powered_rail", 8, 8, 1, '\uE5E4'),
    PRISMARINE(Material.PRISMARINE, "minecraft:block/prismarine", 8, 8, 4, '\uE6F1'),
    PRISMARINE_BRICKS(Material.PRISMARINE_BRICKS, "minecraft:block/prismarine_bricks", 8, 8, 1, '\uE5E5'),
    PRISMARINE_CRYSTALS(Material.PRISMARINE_CRYSTALS, "minecraft:item/prismarine_crystals", 8, 8, 1, '\uE5E6'),
    PRISMARINE_SHARD(Material.PRISMARINE_SHARD, "minecraft:item/prismarine_shard", 8, 8, 1, '\uE5E7'),
    PUFFERFISH(Material.PUFFERFISH, "minecraft:item/pufferfish", 8, 8, 1, '\uE5E8'),
    PUFFERFISH_BUCKET(Material.PUFFERFISH_BUCKET, "minecraft:item/pufferfish_bucket", 8, 8, 1, '\uE5E9'),
    PUMPKIN(Material.PUMPKIN, "minecraft:block/pumpkin_side", 8, 8, 1, '\uE5EA'),
    PUMPKIN_PIE(Material.PUMPKIN_PIE, "minecraft:item/pumpkin_pie", 8, 8, 1, '\uE5EB'),
    PUMPKIN_SEEDS(Material.PUMPKIN_SEEDS, "minecraft:item/pumpkin_seeds", 8, 8, 1, '\uE5EC'),
    PUMPKIN_STEM(Material.PUMPKIN_STEM, "minecraft:block/pumpkin_stem", 8, 8, 1, '\uE5ED'),
    PURPLE_CANDLE(Material.PURPLE_CANDLE, "minecraft:item/purple_candle", 8, 8, 1, '\uE6D5'),
    PURPLE_CONCRETE(Material.PURPLE_CONCRETE, "minecraft:block/purple_concrete", 8, 8, 1, '\uE5EE'),
    PURPLE_CONCRETE_POWDER(Material.PURPLE_CONCRETE_POWDER, "minecraft:block/purple_concrete_powder", 8, 8, 1, '\uE5EF'),
    PURPLE_DYE(Material.PURPLE_DYE, "minecraft:item/purple_dye", 8, 8, 1, '\uE5F0'),
    PURPLE_GLAZED_TERRACOTTA(Material.PURPLE_GLAZED_TERRACOTTA, "minecraft:block/purple_glazed_terracotta", 8, 8, 1, '\uE5F1'),
    PURPLE_SHULKER_BOX(Material.PURPLE_SHULKER_BOX, "minecraft:block/purple_shulker_box", 8, 8, 1, '\uE5F2'),
    PURPLE_STAINED_GLASS(Material.PURPLE_STAINED_GLASS, "minecraft:block/purple_stained_glass", 8, 8, 1, '\uE5F3'),
    PURPLE_STAINED_GLASS_PANE(Material.PURPLE_STAINED_GLASS_PANE, "minecraft:block/purple_stained_glass_pane_top", 8, 8, 1, '\uE70D'),
    PURPLE_TERRACOTTA(Material.PURPLE_TERRACOTTA, "minecraft:block/purple_terracotta", 8, 8, 1, '\uE5F4'),
    PURPLE_WOOL(Material.PURPLE_WOOL, "minecraft:block/purple_wool", 8, 8, 1, '\uE5F5'),
    PURPUR_BLOCK(Material.PURPUR_BLOCK, "minecraft:block/purpur_block", 8, 8, 1, '\uE5F6'),
    PURPUR_PILLAR(Material.PURPUR_PILLAR, "minecraft:block/purpur_pillar", 8, 8, 1, '\uE5F7'),
    QUARTZ(Material.QUARTZ, "minecraft:item/quartz", 8, 8, 1, '\uE5F8'),
    QUARTZ_BLOCK(Material.QUARTZ_BLOCK, "minecraft:block/quartz_block_side", 8, 8, 1, '\uE5F9'),
    QUARTZ_BRICKS(Material.QUARTZ_BRICKS, "minecraft:block/quartz_bricks", 8, 8, 1, '\uE5FA'),
    QUARTZ_PILLAR(Material.QUARTZ_PILLAR, "minecraft:block/quartz_pillar", 8, 8, 1, '\uE5FB'),
    RABBIT(Material.RABBIT, "minecraft:item/rabbit", 8, 8, 1, '\uE5FC'),
    RABBIT_FOOT(Material.RABBIT_FOOT, "minecraft:item/rabbit_foot", 8, 8, 1, '\uE5FD'),
    RABBIT_HIDE(Material.RABBIT_HIDE, "minecraft:item/rabbit_hide", 8, 8, 1, '\uE5FE'),
    RABBIT_STEW(Material.RABBIT_STEW, "minecraft:item/rabbit_stew", 8, 8, 1, '\uE5FF'),
    RAIL(Material.RAIL, "minecraft:block/rail", 8, 8, 1, '\uE600'),
    RAW_COPPER(Material.RAW_COPPER, "minecraft:item/raw_copper", 8, 8, 1, '\uE6D6'),
    RAW_COPPER_BLOCK(Material.RAW_COPPER_BLOCK, "minecraft:block/raw_copper_block", 8, 8, 1, '\uE6D7'),
    RAW_GOLD(Material.RAW_GOLD, "minecraft:item/raw_gold", 8, 8, 1, '\uE6D8'),
    RAW_GOLD_BLOCK(Material.RAW_GOLD_BLOCK, "minecraft:block/raw_gold_block", 8, 8, 1, '\uE6D9'),
    RAW_IRON(Material.RAW_IRON, "minecraft:item/raw_iron", 8, 8, 1, '\uE6DA'),
    RAW_IRON_BLOCK(Material.RAW_IRON_BLOCK, "minecraft:block/raw_iron_block", 8, 8, 1, '\uE6DB'),
    REDSTONE(Material.REDSTONE, "minecraft:item/redstone", 8, 8, 1, '\uE601'),
    REDSTONE_BLOCK(Material.REDSTONE_BLOCK, "minecraft:block/redstone_block", 8, 8, 1, '\uE602'),
    REDSTONE_LAMP(Material.REDSTONE_LAMP, "minecraft:block/redstone_lamp", 8, 8, 1, '\uE603'),
    REDSTONE_ORE(Material.REDSTONE_ORE, "minecraft:block/redstone_ore", 8, 8, 1, '\uE604'),
    REDSTONE_TORCH(Material.REDSTONE_TORCH, "minecraft:block/redstone_torch", 8, 8, 1, '\uE605'),
    RED_CANDLE(Material.RED_CANDLE, "minecraft:item/red_candle", 8, 8, 1, '\uE6DC'),
    RED_CONCRETE(Material.RED_CONCRETE, "minecraft:block/red_concrete", 8, 8, 1, '\uE606'),
    RED_CONCRETE_POWDER(Material.RED_CONCRETE_POWDER, "minecraft:block/red_concrete_powder", 8, 8, 1, '\uE607'),
    RED_DYE(Material.RED_DYE, "minecraft:item/red_dye", 8, 8, 1, '\uE608'),
    RED_GLAZED_TERRACOTTA(Material.RED_GLAZED_TERRACOTTA, "minecraft:block/red_glazed_terracotta", 8, 8, 1, '\uE609'),
    RED_MUSHROOM(Material.RED_MUSHROOM, "minecraft:block/red_mushroom", 8, 8, 1, '\uE60A'),
    RED_MUSHROOM_BLOCK(Material.RED_MUSHROOM_BLOCK, "minecraft:block/red_mushroom_block", 8, 8, 1, '\uE60B'),
    RED_NETHER_BRICKS(Material.RED_NETHER_BRICKS, "minecraft:block/red_nether_bricks", 8, 8, 1, '\uE60C'),
    RED_SAND(Material.RED_SAND, "minecraft:block/red_sand", 8, 8, 1, '\uE60D'),
    RED_SANDSTONE(Material.RED_SANDSTONE, "minecraft:block/red_sandstone", 8, 8, 1, '\uE60E'),
    RED_SHULKER_BOX(Material.RED_SHULKER_BOX, "minecraft:block/red_shulker_box", 8, 8, 1, '\uE60F'),
    RED_STAINED_GLASS(Material.RED_STAINED_GLASS, "minecraft:block/red_stained_glass", 8, 8, 1, '\uE610'),
    RED_STAINED_GLASS_PANE(Material.RED_STAINED_GLASS_PANE, "minecraft:block/red_stained_glass_pane_top", 8, 8, 1, '\uE70E'),
    RED_TERRACOTTA(Material.RED_TERRACOTTA, "minecraft:block/red_terracotta", 8, 8, 1, '\uE611'),
    RED_TULIP(Material.RED_TULIP, "minecraft:block/red_tulip", 8, 8, 1, '\uE612'),
    RED_WOOL(Material.RED_WOOL, "minecraft:block/red_wool", 8, 8, 1, '\uE613'),
    REPEATER(Material.REPEATER, "minecraft:item/repeater", 8, 8, 1, '\uE614'),
    REPEATING_COMMAND_BLOCK(Material.REPEATING_COMMAND_BLOCK, "minecraft:block/repeating_command_block_front", 8, 8, 4, '\uE6F2'),
    RESPAWN_ANCHOR(Material.RESPAWN_ANCHOR, "minecraft:block/respawn_anchor_side0", 8, 8, 1, '\uE6F6'),
    ROOTED_DIRT(Material.ROOTED_DIRT, "minecraft:block/rooted_dirt", 8, 8, 1, '\uE6DD'),
    ROSE_BUSH(Material.ROSE_BUSH, "minecraft:block/rose_bush_top", 8, 8, 1, '\uE70F'),
    ROTTEN_FLESH(Material.ROTTEN_FLESH, "minecraft:item/rotten_flesh", 8, 8, 1, '\uE615'),
    SADDLE(Material.SADDLE, "minecraft:item/saddle", 8, 8, 1, '\uE616'),
    SALMON(Material.SALMON, "minecraft:item/salmon", 8, 8, 1, '\uE617'),
    SALMON_BUCKET(Material.SALMON_BUCKET, "minecraft:item/salmon_bucket", 8, 8, 1, '\uE618'),
    SAND(Material.SAND, "minecraft:block/sand", 8, 8, 1, '\uE619'),
    SANDSTONE(Material.SANDSTONE, "minecraft:block/sandstone", 8, 8, 1, '\uE61A'),
    SCAFFOLDING(Material.SCAFFOLDING, "minecraft:block/scaffolding_side", 8, 8, 1, '\uE61B'),
    SCULK_SENSOR(Material.SCULK_SENSOR, "minecraft:block/sculk_sensor_side", 8, 8, 1, '\uE6DE'),
    SCUTE(Material.SCUTE, "minecraft:item/scute", 8, 8, 1, '\uE61C'),
    SEAGRASS(Material.SEAGRASS, "minecraft:item/seagrass", 8, 8, 1, '\uE61D'),
    SEA_LANTERN(Material.SEA_LANTERN, "minecraft:block/sea_lantern", 8, 8, 5, '\uE6F3'),
    SEA_PICKLE(Material.SEA_PICKLE, "minecraft:item/sea_pickle", 8, 8, 1, '\uE61E'),
    SHEARS(Material.SHEARS, "minecraft:item/shears", 8, 8, 1, '\uE61F'),
    SHROOMLIGHT(Material.SHROOMLIGHT, "minecraft:block/shroomlight", 8, 8, 1, '\uE620'),
    SHULKER_BOX(Material.SHULKER_BOX, "minecraft:block/shulker_box", 8, 8, 1, '\uE621'),
    SHULKER_SHELL(Material.SHULKER_SHELL, "minecraft:item/shulker_shell", 8, 8, 1, '\uE622'),
    SKULL_BANNER_PATTERN(Material.SKULL_BANNER_PATTERN, "minecraft:item/skull_banner_pattern", 8, 8, 1, '\uE623'),
    SLIME_BALL(Material.SLIME_BALL, "minecraft:item/slime_ball", 8, 8, 1, '\uE624'),
    SLIME_BLOCK(Material.SLIME_BLOCK, "minecraft:block/slime_block", 8, 8, 1, '\uE625'),
    SMALL_AMETHYST_BUD(Material.SMALL_AMETHYST_BUD, "minecraft:block/small_amethyst_bud", 8, 8, 1, '\uE6DF'),
    SMALL_DRIPLEAF(Material.SMALL_DRIPLEAF, "minecraft:block/small_dripleaf_stem_bottom", 8, 8, 1, '\uE6E0'),
    SMITHING_TABLE(Material.SMITHING_TABLE, "minecraft:block/smithing_table_front", 8, 8, 1, '\uE626'),
    SMOKER(Material.SMOKER, "minecraft:block/smoker_front", 8, 8, 1, '\uE627'),
    SMOOTH_BASALT(Material.SMOOTH_BASALT, "minecraft:block/smooth_basalt", 8, 8, 1, '\uE6E1'),
    SMOOTH_QUARTZ(Material.SMOOTH_QUARTZ, "minecraft:block/quartz_block_bottom", 8, 8, 1, '\uE6F9'),
    SMOOTH_RED_SANDSTONE(Material.SMOOTH_RED_SANDSTONE, "minecraft:block/red_sandstone_top", 8, 8, 1, '\uE6F7'),
    SMOOTH_SANDSTONE(Material.SMOOTH_SANDSTONE, "minecraft:block/sandstone_top", 8, 8, 1, '\uE6F8'),
    SMOOTH_STONE(Material.SMOOTH_STONE, "minecraft:block/smooth_stone", 8, 8, 1, '\uE628'),
    SMOOTH_STONE_SLAB(Material.SMOOTH_STONE_SLAB, "minecraft:block/smooth_stone_slab_side", 8, 8, 1, '\uE629'),
    SNOW(Material.SNOW, "minecraft:block/snow", 8, 8, 1, '\uE62A'),
    SNOWBALL(Material.SNOWBALL, "minecraft:item/snowball", 8, 8, 1, '\uE62B'),
    SOUL_CAMPFIRE(Material.SOUL_CAMPFIRE, "minecraft:item/soul_campfire", 8, 8, 1, '\uE62C'),
    SOUL_LANTERN(Material.SOUL_LANTERN, "minecraft:item/soul_lantern", 8, 8, 1, '\uE62D'),
    SOUL_SAND(Material.SOUL_SAND, "minecraft:block/soul_sand", 8, 8, 1, '\uE62E'),
    SOUL_SOIL(Material.SOUL_SOIL, "minecraft:block/soul_soil", 8, 8, 1, '\uE62F'),
    SOUL_TORCH(Material.SOUL_TORCH, "minecraft:block/soul_torch", 8, 8, 1, '\uE630'),
    SPAWNER(Material.SPAWNER, "minecraft:block/spawner", 8, 8, 1, '\uE631'),
    SPECTRAL_ARROW(Material.SPECTRAL_ARROW, "minecraft:item/spectral_arrow", 8, 8, 1, '\uE632'),
    SPIDER_EYE(Material.SPIDER_EYE, "minecraft:item/spider_eye", 8, 8, 1, '\uE633'),
    SPLASH_POTION(Material.SPLASH_POTION, "minecraft:item/splash_potion", 8, 8, 1, '\uE634'),
    SPONGE(Material.SPONGE, "minecraft:block/sponge", 8, 8, 1, '\uE635'),
    SPORE_BLOSSOM(Material.SPORE_BLOSSOM, "minecraft:block/spore_blossom", 8, 8, 1, '\uE6E2'),
    SPRUCE_BOAT(Material.SPRUCE_BOAT, "minecraft:item/spruce_boat", 8, 8, 1, '\uE636'),
    SPRUCE_DOOR(Material.SPRUCE_DOOR, "minecraft:item/spruce_door", 8, 8, 1, '\uE637'),
    SPRUCE_LEAVES(Material.SPRUCE_LEAVES, "minecraft:block/spruce_leaves", 8, 8, 1, '\uE638'),
    SPRUCE_LOG(Material.SPRUCE_LOG, "minecraft:block/spruce_log", 8, 8, 1, '\uE639'),
    SPRUCE_PLANKS(Material.SPRUCE_PLANKS, "minecraft:block/spruce_planks", 8, 8, 1, '\uE63A'),
    SPRUCE_SAPLING(Material.SPRUCE_SAPLING, "minecraft:block/spruce_sapling", 8, 8, 1, '\uE63B'),
    SPRUCE_SIGN(Material.SPRUCE_SIGN, "minecraft:item/spruce_sign", 8, 8, 1, '\uE63C'),
    SPRUCE_TRAPDOOR(Material.SPRUCE_TRAPDOOR, "minecraft:block/spruce_trapdoor", 8, 8, 1, '\uE63D'),
    SPYGLASS(Material.SPYGLASS, "minecraft:item/spyglass", 8, 8, 1, '\uE6E3'),
    STICK(Material.STICK, "minecraft:item/stick", 8, 8, 1, '\uE63E'),
    STICKY_PISTON(Material.STICKY_PISTON, "minecraft:block/piston_top_sticky", 8, 8, 1, '\uE719'),
    STONE(Material.STONE, "minecraft:block/stone", 8, 8, 1, '\uE63F'),
    STONECUTTER(Material.STONECUTTER, "minecraft:block/stonecutter_side", 8, 8, 1, '\uE640'),
    STONE_AXE(Material.STONE_AXE, "minecraft:item/stone_axe", 8, 8, 1, '\uE641'),
    STONE_BRICKS(Material.STONE_BRICKS, "minecraft:block/stone_bricks", 8, 8, 1, '\uE642'),
    STONE_HOE(Material.STONE_HOE, "minecraft:item/stone_hoe", 8, 8, 1, '\uE643'),
    STONE_PICKAXE(Material.STONE_PICKAXE, "minecraft:item/stone_pickaxe", 8, 8, 1, '\uE644'),
    STONE_SHOVEL(Material.STONE_SHOVEL, "minecraft:item/stone_shovel", 8, 8, 1, '\uE645'),
    STONE_SWORD(Material.STONE_SWORD, "minecraft:item/stone_sword", 8, 8, 1, '\uE646'),
    STRING(Material.STRING, "minecraft:item/string", 8, 8, 1, '\uE647'),
    STRIPPED_ACACIA_LOG(Material.STRIPPED_ACACIA_LOG, "minecraft:block/stripped_acacia_log", 8, 8, 1, '\uE648'),
    STRIPPED_BIRCH_LOG(Material.STRIPPED_BIRCH_LOG, "minecraft:block/stripped_birch_log", 8, 8, 1, '\uE649'),
    STRIPPED_CRIMSON_STEM(Material.STRIPPED_CRIMSON_STEM, "minecraft:block/stripped_crimson_stem", 8, 8, 1, '\uE64A'),
    STRIPPED_DARK_OAK_LOG(Material.STRIPPED_DARK_OAK_LOG, "minecraft:block/stripped_dark_oak_log", 8, 8, 1, '\uE64B'),
    STRIPPED_JUNGLE_LOG(Material.STRIPPED_JUNGLE_LOG, "minecraft:block/stripped_jungle_log", 8, 8, 1, '\uE64C'),
    STRIPPED_OAK_LOG(Material.STRIPPED_OAK_LOG, "minecraft:block/stripped_oak_log", 8, 8, 1, '\uE64D'),
    STRIPPED_SPRUCE_LOG(Material.STRIPPED_SPRUCE_LOG, "minecraft:block/stripped_spruce_log", 8, 8, 1, '\uE64E'),
    STRIPPED_WARPED_STEM(Material.STRIPPED_WARPED_STEM, "minecraft:block/stripped_warped_stem", 8, 8, 1, '\uE64F'),
    STRUCTURE_BLOCK(Material.STRUCTURE_BLOCK, "minecraft:block/structure_block", 8, 8, 1, '\uE650'),
    STRUCTURE_VOID(Material.STRUCTURE_VOID, "minecraft:item/structure_void", 8, 8, 1, '\uE651'),
    SUGAR(Material.SUGAR, "minecraft:item/sugar", 8, 8, 1, '\uE652'),
    SUGAR_CANE(Material.SUGAR_CANE, "minecraft:item/sugar_cane", 8, 8, 1, '\uE653'),
    SUNFLOWER(Material.SUNFLOWER, "minecraft:block/sunflower_front", 8, 8, 1, '\uE710'),
    SUSPICIOUS_STEW(Material.SUSPICIOUS_STEW, "minecraft:item/suspicious_stew", 8, 8, 1, '\uE654'),
    SWEET_BERRIES(Material.SWEET_BERRIES, "minecraft:item/sweet_berries", 8, 8, 1, '\uE655'),
    TALL_GRASS(Material.TALL_GRASS, "minecraft:block/tall_grass_top", 8, 8, 1, '\uE711'),
    TARGET(Material.TARGET, "minecraft:block/target_side", 8, 8, 1, '\uE656'),
    TERRACOTTA(Material.TERRACOTTA, "minecraft:block/terracotta", 8, 8, 1, '\uE657'),
    TINTED_GLASS(Material.TINTED_GLASS, "minecraft:block/tinted_glass", 8, 8, 1, '\uE6E4'),
    TIPPED_ARROW(Material.TIPPED_ARROW, "minecraft:item/tipped_arrow_base", 8, 8, 1, '\uE712'),
    TNT(Material.TNT, "minecraft:block/tnt_side", 8, 8, 1, '\uE658'),
    TNT_MINECART(Material.TNT_MINECART, "minecraft:item/tnt_minecart", 8, 8, 1, '\uE659'),
    TORCH(Material.TORCH, "minecraft:block/torch", 8, 8, 1, '\uE65A'),
    TOTEM_OF_UNDYING(Material.TOTEM_OF_UNDYING, "minecraft:item/totem_of_undying", 8, 8, 1, '\uE65B'),
    TRIDENT(Material.TRIDENT, "minecraft:item/trident", 8, 8, 1, '\uE65C'),
    TRIPWIRE(Material.TRIPWIRE, "minecraft:block/tripwire", 8, 8, 1, '\uE65D'),
    TRIPWIRE_HOOK(Material.TRIPWIRE_HOOK, "minecraft:block/tripwire_hook", 8, 8, 1, '\uE65E'),
    TROPICAL_FISH(Material.TROPICAL_FISH, "minecraft:item/tropical_fish", 8, 8, 1, '\uE65F'),
    TROPICAL_FISH_BUCKET(Material.TROPICAL_FISH_BUCKET, "minecraft:item/tropical_fish_bucket", 8, 8, 1, '\uE660'),
    TUBE_CORAL(Material.TUBE_CORAL, "minecraft:block/tube_coral", 8, 8, 1, '\uE661'),
    TUBE_CORAL_BLOCK(Material.TUBE_CORAL_BLOCK, "minecraft:block/tube_coral_block", 8, 8, 1, '\uE662'),
    TUBE_CORAL_FAN(Material.TUBE_CORAL_FAN, "minecraft:block/tube_coral_fan", 8, 8, 1, '\uE663'),
    TUFF(Material.TUFF, "minecraft:block/tuff", 8, 8, 1, '\uE6E5'),
    TURTLE_EGG(Material.TURTLE_EGG, "minecraft:item/turtle_egg", 8, 8, 1, '\uE664'),
    TURTLE_HELMET(Material.TURTLE_HELMET, "minecraft:item/turtle_helmet", 8, 8, 1, '\uE665'),
    TWISTING_VINES(Material.TWISTING_VINES, "minecraft:block/twisting_vines", 8, 8, 1, '\uE666'),
    TWISTING_VINES_PLANT(Material.TWISTING_VINES_PLANT, "minecraft:block/twisting_vines_plant", 8, 8, 1, '\uE667'),
    VINE(Material.VINE, "minecraft:block/vine", 8, 8, 1, '\uE668'),
    WARPED_DOOR(Material.WARPED_DOOR, "minecraft:item/warped_door", 8, 8, 1, '\uE669'),
    WARPED_FUNGUS(Material.WARPED_FUNGUS, "minecraft:block/warped_fungus", 8, 8, 1, '\uE66A'),
    WARPED_FUNGUS_ON_A_STICK(Material.WARPED_FUNGUS_ON_A_STICK, "minecraft:item/warped_fungus_on_a_stick", 8, 8, 1, '\uE66B'),
    WARPED_NYLIUM(Material.WARPED_NYLIUM, "minecraft:block/warped_nylium", 8, 8, 1, '\uE66C'),
    WARPED_PLANKS(Material.WARPED_PLANKS, "minecraft:block/warped_planks", 8, 8, 1, '\uE66D'),
    WARPED_ROOTS(Material.WARPED_ROOTS, "minecraft:block/warped_roots", 8, 8, 1, '\uE66E'),
    WARPED_SIGN(Material.WARPED_SIGN, "minecraft:item/warped_sign", 8, 8, 1, '\uE66F'),
    WARPED_STEM(Material.WARPED_STEM, "minecraft:block/warped_stem", 8, 8, 5, '\uE6F4'),
    WARPED_TRAPDOOR(Material.WARPED_TRAPDOOR, "minecraft:block/warped_trapdoor", 8, 8, 1, '\uE670'),
    WARPED_WART_BLOCK(Material.WARPED_WART_BLOCK, "minecraft:block/warped_wart_block", 8, 8, 1, '\uE671'),
    WATER_BUCKET(Material.WATER_BUCKET, "minecraft:item/water_bucket", 8, 8, 1, '\uE672'),
    WEATHERED_COPPER(Material.WEATHERED_COPPER, "minecraft:block/weathered_copper", 8, 8, 1, '\uE6E6'),
    WEATHERED_CUT_COPPER(Material.WEATHERED_CUT_COPPER, "minecraft:block/weathered_cut_copper", 8, 8, 1, '\uE6E7'),
    WEEPING_VINES(Material.WEEPING_VINES, "minecraft:block/weeping_vines", 8, 8, 1, '\uE673'),
    WEEPING_VINES_PLANT(Material.WEEPING_VINES_PLANT, "minecraft:block/weeping_vines_plant", 8, 8, 1, '\uE674'),
    WET_SPONGE(Material.WET_SPONGE, "minecraft:block/wet_sponge", 8, 8, 1, '\uE675'),
    WHEAT(Material.WHEAT, "minecraft:item/wheat", 8, 8, 1, '\uE676'),
    WHEAT_SEEDS(Material.WHEAT_SEEDS, "minecraft:item/wheat_seeds", 8, 8, 1, '\uE677'),
    WHITE_CANDLE(Material.WHITE_CANDLE, "minecraft:item/white_candle", 8, 8, 1, '\uE6E8'),
    WHITE_CONCRETE(Material.WHITE_CONCRETE, "minecraft:block/white_concrete", 8, 8, 1, '\uE678'),
    WHITE_CONCRETE_POWDER(Material.WHITE_CONCRETE_POWDER, "minecraft:block/white_concrete_powder", 8, 8, 1, '\uE679'),
    WHITE_DYE(Material.WHITE_DYE, "minecraft:item/white_dye", 8, 8, 1, '\uE67A'),
    WHITE_GLAZED_TERRACOTTA(Material.WHITE_GLAZED_TERRACOTTA, "minecraft:block/white_glazed_terracotta", 8, 8, 1, '\uE67B'),
    WHITE_SHULKER_BOX(Material.WHITE_SHULKER_BOX, "minecraft:block/white_shulker_box", 8, 8, 1, '\uE67C'),
    WHITE_STAINED_GLASS(Material.WHITE_STAINED_GLASS, "minecraft:block/white_stained_glass", 8, 8, 1, '\uE67D'),
    WHITE_STAINED_GLASS_PANE(Material.WHITE_STAINED_GLASS_PANE, "minecraft:block/white_stained_glass_pane_top", 8, 8, 1, '\uE713'),
    WHITE_TERRACOTTA(Material.WHITE_TERRACOTTA, "minecraft:block/white_terracotta", 8, 8, 1, '\uE67E'),
    WHITE_TULIP(Material.WHITE_TULIP, "minecraft:block/white_tulip", 8, 8, 1, '\uE67F'),
    WHITE_WOOL(Material.WHITE_WOOL, "minecraft:block/white_wool", 8, 8, 1, '\uE680'),
    WITHER_ROSE(Material.WITHER_ROSE, "minecraft:block/wither_rose", 8, 8, 1, '\uE681'),
    WOODEN_AXE(Material.WOODEN_AXE, "minecraft:item/wooden_axe", 8, 8, 1, '\uE682'),
    WOODEN_HOE(Material.WOODEN_HOE, "minecraft:item/wooden_hoe", 8, 8, 1, '\uE683'),
    WOODEN_PICKAXE(Material.WOODEN_PICKAXE, "minecraft:item/wooden_pickaxe", 8, 8, 1, '\uE684'),
    WOODEN_SHOVEL(Material.WOODEN_SHOVEL, "minecraft:item/wooden_shovel", 8, 8, 1, '\uE685'),
    WOODEN_SWORD(Material.WOODEN_SWORD, "minecraft:item/wooden_sword", 8, 8, 1, '\uE686'),
    WRITABLE_BOOK(Material.WRITABLE_BOOK, "minecraft:item/writable_book", 8, 8, 1, '\uE687'),
    WRITTEN_BOOK(Material.WRITTEN_BOOK, "minecraft:item/written_book", 8, 8, 1, '\uE688'),
    YELLOW_CANDLE(Material.YELLOW_CANDLE, "minecraft:item/yellow_candle", 8, 8, 1, '\uE6E9'),
    YELLOW_CONCRETE(Material.YELLOW_CONCRETE, "minecraft:block/yellow_concrete", 8, 8, 1, '\uE689'),
    YELLOW_CONCRETE_POWDER(Material.YELLOW_CONCRETE_POWDER, "minecraft:block/yellow_concrete_powder", 8, 8, 1, '\uE68A'),
    YELLOW_DYE(Material.YELLOW_DYE, "minecraft:item/yellow_dye", 8, 8, 1, '\uE68B'),
    YELLOW_GLAZED_TERRACOTTA(Material.YELLOW_GLAZED_TERRACOTTA, "minecraft:block/yellow_glazed_terracotta", 8, 8, 1, '\uE68C'),
    YELLOW_SHULKER_BOX(Material.YELLOW_SHULKER_BOX, "minecraft:block/yellow_shulker_box", 8, 8, 1, '\uE68D'),
    YELLOW_STAINED_GLASS(Material.YELLOW_STAINED_GLASS, "minecraft:block/yellow_stained_glass", 8, 8, 1, '\uE68E'),
    YELLOW_STAINED_GLASS_PANE(Material.YELLOW_STAINED_GLASS_PANE, "minecraft:block/yellow_stained_glass_pane_top", 8, 8, 1, '\uE714'),
    YELLOW_TERRACOTTA(Material.YELLOW_TERRACOTTA, "minecraft:block/yellow_terracotta", 8, 8, 1, '\uE68F'),
    YELLOW_WOOL(Material.YELLOW_WOOL, "minecraft:block/yellow_wool", 8, 8, 1, '\uE690'),
    ;

    public final Material material;
    public final String filename;
    public final int ascent;
    public final int height;
    public final int rows;
    public final char character;
    public final Component component;
    private static final Map<Material, VanillaItems> MATERIAL_MAP = new EnumMap<>(Material.class);

    VanillaItems(final Material material, final String filename, final int ascent, final int height, final int rows, final char character) {
        this.material = material;
        this.filename = filename;
        this.ascent = ascent;
        this.height = height;
        this.rows = rows;
        this.character = character;
        final TextColor color;
        switch (material) {
        case GRASS:
        case OAK_LEAVES:
        case SPRUCE_LEAVES:
        case BIRCH_LEAVES:
        case ACACIA_LEAVES:
        case DARK_OAK_LEAVES:
        case JUNGLE_LEAVES:
        case VINE:
        case LILY_PAD:
        case FERN:
        case TALL_GRASS:
        case LARGE_FERN:
            color = TextColor.color(0x00FF00);
            break;
        default:
            color = TextColor.color(0xFFFFFF);
            break;
        }
        this.component = Component.text(character)
            .style(Style.style()
                   .font(Key.key("cavetale:default"))
                   .color(color));
    }

    static {
        for (VanillaItems it : VanillaItems.values()) {
            MATERIAL_MAP.put(it.material, it);
        }
        MATERIAL_MAP.put(Material.HEAVY_WEIGHTED_PRESSURE_PLATE, IRON_BLOCK);
        MATERIAL_MAP.put(Material.LIGHT_WEIGHTED_PRESSURE_PLATE, GOLD_BLOCK);
        MATERIAL_MAP.put(Material.DEBUG_STICK, STICK);
        MATERIAL_MAP.put(Material.ENCHANTED_GOLDEN_APPLE, GOLDEN_APPLE);
        MATERIAL_MAP.put(Material.SNOW_BLOCK, SNOW);
        for (Material material : Material.values()) {
            if (MATERIAL_MAP.containsKey(material)) continue;
            if (material.isLegacy()) continue;
            if (!material.isItem()) continue;
            if (material.isAir()) continue;
            String name = material.name();
            if (name.startsWith("WAXED_")) {
                name = name.substring(6); // modifying!
                try {
                    VanillaItems it = VanillaItems.valueOf(name);
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
            } else if (name.startsWith("PETRIFIED_")) {
                name = name.substring(10); // modifying!
                try {
                    VanillaItems it = VanillaItems.valueOf(name);
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
            }
            if (name.endsWith("_STAIRS")) {
                String sub = name.substring(0, name.length() - 7);
                try {
                    VanillaItems it = VanillaItems.valueOf(sub);
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
            }
            if (name.endsWith("_SLAB")) {
                String sub = name.substring(0, name.length() - 5);
                try {
                    VanillaItems it = VanillaItems.valueOf(sub);
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
                try { // OAK_SLAB => OAK_PLANKS
                    VanillaItems it = VanillaItems.valueOf(sub + "_PLANKS");
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
                try { // PURPUR_SLAB => PURPUR_BLOCK
                    VanillaItems it = VanillaItems.valueOf(sub + "_BLOCK");
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
                try { // STONE_BRICK_SLAB => STONE_BRICKS
                    VanillaItems it = VanillaItems.valueOf(sub + "S");
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
            }
            if (name.endsWith("_FENCE")) {
                String sub = name.substring(0, name.length() - 6);
                try { // OAK_FENCE => OAK_PLANKS
                    VanillaItems it = VanillaItems.valueOf(sub + "_PLANKS");
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
                try { // NETHER_BRICK_FENCE => NETHER_BRICKS
                    VanillaItems it = VanillaItems.valueOf(sub + "S");
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
            }
            if (name.endsWith("_FENCE_GATE")) {
                String sub = name.substring(0, name.length() - 11);
                try { // OAK_FENCE_GATE => OAK_PLANKS
                    VanillaItems it = VanillaItems.valueOf(sub + "_PLANKS");
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
            }
            if (name.endsWith("_WOOD")) {
                String sub = name.substring(0, name.length() - 5);
                try {
                    VanillaItems it = VanillaItems.valueOf(sub + "_LOG");
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
            }
            if (name.endsWith("_CARPET")) {
                String sub = name.substring(0, name.length() - 7);
                try { // MOSS_CARPET => MOSS_BLOCk
                    VanillaItems it = VanillaItems.valueOf(sub + "_BLOCK");
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
                try { // BLUE_CARPET => BLUE_WOOL
                    VanillaItems it = VanillaItems.valueOf(sub + "_WOOL");
                    MATERIAL_MAP.put(material, it);
                    continue;
                } catch (IllegalArgumentException iae) { }
            }
            if (name.endsWith("_HYPHAE")) {
                if (insertHelper(material, name.substring(0, name.length() - 7) + "_STEM")) continue;
            }
            for (String suffix : List.of("_BANNER", "_BED")) {
                if (name.endsWith(suffix)) {
                    if (insertHelper(material, name.substring(0, name.length() - suffix.length()) + "_WOOL")) continue;
                }
            }
            for (String suffix : List.of("_BUTTON",
                                         "_SLAB",
                                         "_STAIRS",
                                         "_PRESSURE_PLATE",
                                         "_WALL")) {
                if (name.endsWith(suffix)) {
                    String sub = name.substring(0, name.length() - suffix.length());
                    if (insertHelper(material, sub)) continue;
                    if (insertHelper(material, sub + "_PLANKS")) continue;
                    if (insertHelper(material, sub + "_BLOCK")) continue;
                    if (insertHelper(material, sub + "S")) continue;
                }
            }
            for (String prefix : List.of("INFESTED_")) {
                if (name.startsWith(prefix)) {
                    String sub = name.substring(prefix.length());
                    if (insertHelper(material, sub)) continue;
                }
            }
        }
    }

    private static boolean insertHelper(Material mat, String sub) {
        VanillaItems it = VanillaItems.of(sub);
        if (it != null) {
            MATERIAL_MAP.put(mat, it);
            return true;
        } else {
            return false;
        }
    }

    public GlyphPolicy getPolicy() {
        return GlyphPolicy.PUBLIC;
    }

    public static VanillaItems of(Material material) {
        return MATERIAL_MAP.get(material);
    }

    public static VanillaItems of(String key) {
        try {
            return VanillaItems.valueOf(key.toUpperCase());
        } catch (IllegalArgumentException iae) {
            return null;
        }
    }

    public static Component componentOf(Material material) {
        VanillaItems glyph = VanillaItems.of(material);
        return glyph != null ? glyph.component : Component.empty();
    }
}
